// Code generated by protoc-gen-go. DO NOT EDIT.
// source: OnlineSolutions.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Adult                uint32   `protobuf:"varint,5,opt,name=adult,proto3" json:"adult,omitempty"`
	Child                uint32   `protobuf:"varint,6,opt,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SearchRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SearchRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *SearchRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *SearchRequest) GetAdult() uint32 {
	if m != nil {
		return m.Adult
	}
	return 0
}

func (m *SearchRequest) GetChild() uint32 {
	if m != nil {
		return m.Child
	}
	return 0
}

type AsyncKeyResponse struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncKeyResponse) Reset()         { *m = AsyncKeyResponse{} }
func (m *AsyncKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncKeyResponse) ProtoMessage()    {}
func (*AsyncKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{1}
}

func (m *AsyncKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncKeyResponse.Unmarshal(m, b)
}
func (m *AsyncKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncKeyResponse.Marshal(b, m, deterministic)
}
func (m *AsyncKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncKeyResponse.Merge(m, src)
}
func (m *AsyncKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AsyncKeyResponse.Size(m)
}
func (m *AsyncKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncKeyResponse proto.InternalMessageInfo

func (m *AsyncKeyResponse) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type OnlineSolutionsAsyncQueryRequest struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineSolutionsAsyncQueryRequest) Reset()         { *m = OnlineSolutionsAsyncQueryRequest{} }
func (m *OnlineSolutionsAsyncQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OnlineSolutionsAsyncQueryRequest) ProtoMessage()    {}
func (*OnlineSolutionsAsyncQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{2}
}

func (m *OnlineSolutionsAsyncQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineSolutionsAsyncQueryRequest.Unmarshal(m, b)
}
func (m *OnlineSolutionsAsyncQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineSolutionsAsyncQueryRequest.Marshal(b, m, deterministic)
}
func (m *OnlineSolutionsAsyncQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineSolutionsAsyncQueryRequest.Merge(m, src)
}
func (m *OnlineSolutionsAsyncQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OnlineSolutionsAsyncQueryRequest.Size(m)
}
func (m *OnlineSolutionsAsyncQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineSolutionsAsyncQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineSolutionsAsyncQueryRequest proto.InternalMessageInfo

func (m *OnlineSolutionsAsyncQueryRequest) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type OnlineSolutionsResponse struct {
	RailwaySolutions     []*RailwaySolution `protobuf:"bytes,1,rep,name=railway_solutions,json=railwaySolutions,proto3" json:"railway_solutions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OnlineSolutionsResponse) Reset()         { *m = OnlineSolutionsResponse{} }
func (m *OnlineSolutionsResponse) String() string { return proto.CompactTextString(m) }
func (*OnlineSolutionsResponse) ProtoMessage()    {}
func (*OnlineSolutionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{3}
}

func (m *OnlineSolutionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineSolutionsResponse.Unmarshal(m, b)
}
func (m *OnlineSolutionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineSolutionsResponse.Marshal(b, m, deterministic)
}
func (m *OnlineSolutionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineSolutionsResponse.Merge(m, src)
}
func (m *OnlineSolutionsResponse) XXX_Size() int {
	return xxx_messageInfo_OnlineSolutionsResponse.Size(m)
}
func (m *OnlineSolutionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineSolutionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineSolutionsResponse proto.InternalMessageInfo

func (m *OnlineSolutionsResponse) GetRailwaySolutions() []*RailwaySolution {
	if m != nil {
		return m.RailwaySolutions
	}
	return nil
}

type RailwaySolution struct {
	Railway              *Railway    `protobuf:"bytes,1,opt,name=railway,proto3" json:"railway,omitempty"`
	Loading              bool        `protobuf:"varint,2,opt,name=loading,proto3" json:"loading,omitempty"`
	Solutions            []*Solution `protobuf:"bytes,3,rep,name=solutions,proto3" json:"solutions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RailwaySolution) Reset()         { *m = RailwaySolution{} }
func (m *RailwaySolution) String() string { return proto.CompactTextString(m) }
func (*RailwaySolution) ProtoMessage()    {}
func (*RailwaySolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{4}
}

func (m *RailwaySolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RailwaySolution.Unmarshal(m, b)
}
func (m *RailwaySolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RailwaySolution.Marshal(b, m, deterministic)
}
func (m *RailwaySolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RailwaySolution.Merge(m, src)
}
func (m *RailwaySolution) XXX_Size() int {
	return xxx_messageInfo_RailwaySolution.Size(m)
}
func (m *RailwaySolution) XXX_DiscardUnknown() {
	xxx_messageInfo_RailwaySolution.DiscardUnknown(m)
}

var xxx_messageInfo_RailwaySolution proto.InternalMessageInfo

func (m *RailwaySolution) GetRailway() *Railway {
	if m != nil {
		return m.Railway
	}
	return nil
}

func (m *RailwaySolution) GetLoading() bool {
	if m != nil {
		return m.Loading
	}
	return false
}

func (m *RailwaySolution) GetSolutions() []*Solution {
	if m != nil {
		return m.Solutions
	}
	return nil
}

type Railway struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Railway) Reset()         { *m = Railway{} }
func (m *Railway) String() string { return proto.CompactTextString(m) }
func (*Railway) ProtoMessage()    {}
func (*Railway) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{5}
}

func (m *Railway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Railway.Unmarshal(m, b)
}
func (m *Railway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Railway.Marshal(b, m, deterministic)
}
func (m *Railway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Railway.Merge(m, src)
}
func (m *Railway) XXX_Size() int {
	return xxx_messageInfo_Railway.Size(m)
}
func (m *Railway) XXX_DiscardUnknown() {
	xxx_messageInfo_Railway.DiscardUnknown(m)
}

var xxx_messageInfo_Railway proto.InternalMessageInfo

func (m *Railway) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Station struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	HelpUrl              string   `protobuf:"bytes,3,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{6}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Station) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

type Duration struct {
	Hour                 uint32   `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minutes              uint32   `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{7}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetHour() uint32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *Duration) GetMinutes() uint32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

type Solution struct {
	From                 *Station   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Departure            string     `protobuf:"bytes,3,opt,name=departure,proto3" json:"departure,omitempty"`
	TransferTimes        uint32     `protobuf:"varint,4,opt,name=transfer_times,json=transferTimes,proto3" json:"transfer_times,omitempty"`
	Duration             *Duration  `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Sections             []*Section `protobuf:"bytes,6,rep,name=sections,proto3" json:"sections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Solution) Reset()         { *m = Solution{} }
func (m *Solution) String() string { return proto.CompactTextString(m) }
func (*Solution) ProtoMessage()    {}
func (*Solution) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{8}
}

func (m *Solution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solution.Unmarshal(m, b)
}
func (m *Solution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solution.Marshal(b, m, deterministic)
}
func (m *Solution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solution.Merge(m, src)
}
func (m *Solution) XXX_Size() int {
	return xxx_messageInfo_Solution.Size(m)
}
func (m *Solution) XXX_DiscardUnknown() {
	xxx_messageInfo_Solution.DiscardUnknown(m)
}

var xxx_messageInfo_Solution proto.InternalMessageInfo

func (m *Solution) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Solution) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Solution) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Solution) GetTransferTimes() uint32 {
	if m != nil {
		return m.TransferTimes
	}
	return 0
}

func (m *Solution) GetDuration() *Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Solution) GetSections() []*Section {
	if m != nil {
		return m.Sections
	}
	return nil
}

type Section struct {
	CarrierCode          string   `protobuf:"bytes,1,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	CarrierDescription   string   `protobuf:"bytes,2,opt,name=carrier_description,json=carrierDescription,proto3" json:"carrier_description,omitempty"`
	CarrierIcon          string   `protobuf:"bytes,3,opt,name=carrier_icon,json=carrierIcon,proto3" json:"carrier_icon,omitempty"`
	Offers               []*Offer `protobuf:"bytes,4,rep,name=offers,proto3" json:"offers,omitempty"`
	Trains               []*Train `protobuf:"bytes,5,rep,name=trains,proto3" json:"trains,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Section) Reset()         { *m = Section{} }
func (m *Section) String() string { return proto.CompactTextString(m) }
func (*Section) ProtoMessage()    {}
func (*Section) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{9}
}

func (m *Section) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Section.Unmarshal(m, b)
}
func (m *Section) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Section.Marshal(b, m, deterministic)
}
func (m *Section) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Section.Merge(m, src)
}
func (m *Section) XXX_Size() int {
	return xxx_messageInfo_Section.Size(m)
}
func (m *Section) XXX_DiscardUnknown() {
	xxx_messageInfo_Section.DiscardUnknown(m)
}

var xxx_messageInfo_Section proto.InternalMessageInfo

func (m *Section) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *Section) GetCarrierDescription() string {
	if m != nil {
		return m.CarrierDescription
	}
	return ""
}

func (m *Section) GetCarrierIcon() string {
	if m != nil {
		return m.CarrierIcon
	}
	return ""
}

func (m *Section) GetOffers() []*Offer {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *Section) GetTrains() []*Train {
	if m != nil {
		return m.Trains
	}
	return nil
}

type Offer struct {
	Code                 string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Detail               string     `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	HelpUrl              string     `protobuf:"bytes,4,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	Restriction          string     `protobuf:"bytes,5,opt,name=restriction,proto3" json:"restriction,omitempty"`
	TicketType           string     `protobuf:"bytes,6,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	SeatType             string     `protobuf:"bytes,7,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	RefundType           string     `protobuf:"bytes,8,opt,name=refund_type,json=refundType,proto3" json:"refund_type,omitempty"`
	ConfirmAgain         string     `protobuf:"bytes,9,opt,name=confirm_again,json=confirmAgain,proto3" json:"confirm_again,omitempty"`
	ChangeType           string     `protobuf:"bytes,10,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Services             []*Service `protobuf:"bytes,11,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{10}
}

func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Offer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Offer) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Offer) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

func (m *Offer) GetRestriction() string {
	if m != nil {
		return m.Restriction
	}
	return ""
}

func (m *Offer) GetTicketType() string {
	if m != nil {
		return m.TicketType
	}
	return ""
}

func (m *Offer) GetSeatType() string {
	if m != nil {
		return m.SeatType
	}
	return ""
}

func (m *Offer) GetRefundType() string {
	if m != nil {
		return m.RefundType
	}
	return ""
}

func (m *Offer) GetConfirmAgain() string {
	if m != nil {
		return m.ConfirmAgain
	}
	return ""
}

func (m *Offer) GetChangeType() string {
	if m != nil {
		return m.ChangeType
	}
	return ""
}

func (m *Offer) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Price                  *Price        `protobuf:"bytes,31,opt,name=price,proto3" json:"price,omitempty"`
	AverageUnitPrice       *Price        `protobuf:"bytes,32,opt,name=average_unit_price,json=averageUnitPrice,proto3" json:"average_unit_price,omitempty"`
	Available              *Availability `protobuf:"bytes,33,opt,name=available,proto3" json:"available,omitempty"`
	Code                   string        `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description            string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Detail                 string        `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	FeaturePhoto           string        `protobuf:"bytes,4,opt,name=feature_photo,json=featurePhoto,proto3" json:"feature_photo,omitempty"`
	BookingCode            string        `protobuf:"bytes,5,opt,name=booking_code,json=bookingCode,proto3" json:"booking_code,omitempty"`
	BookingType            string        `protobuf:"bytes,6,opt,name=booking_type,json=bookingType,proto3" json:"booking_type,omitempty"`
	HasWifi                string        `protobuf:"bytes,7,opt,name=has_wifi,json=hasWifi,proto3" json:"has_wifi,omitempty"`
	HasPowerOutlet         string        `protobuf:"bytes,8,opt,name=has_power_outlet,json=hasPowerOutlet,proto3" json:"has_power_outlet,omitempty"`
	HasAirConditioning     string        `protobuf:"bytes,9,opt,name=has_air_conditioning,json=hasAirConditioning,proto3" json:"has_air_conditioning,omitempty"`
	HasEntertainmentSystem string        `protobuf:"bytes,10,opt,name=has_entertainment_system,json=hasEntertainmentSystem,proto3" json:"has_entertainment_system,omitempty"`
	HasReadingLight        string        `protobuf:"bytes,11,opt,name=has_reading_light,json=hasReadingLight,proto3" json:"has_reading_light,omitempty"`
	SeatReservation        string        `protobuf:"bytes,12,opt,name=seat_reservation,json=seatReservation,proto3" json:"seat_reservation,omitempty"`
	SeatType               string        `protobuf:"bytes,13,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`
	NumberOfSeatsPerRow    string        `protobuf:"bytes,14,opt,name=number_of_seats_per_row,json=numberOfSeatsPerRow,proto3" json:"number_of_seats_per_row,omitempty"`
	BedType                string        `protobuf:"bytes,15,opt,name=bed_type,json=bedType,proto3" json:"bed_type,omitempty"`
	ToiletType             string        `protobuf:"bytes,16,opt,name=toilet_type,json=toiletType,proto3" json:"toilet_type,omitempty"`
	FoodServiceType        string        `protobuf:"bytes,17,opt,name=food_service_type,json=foodServiceType,proto3" json:"food_service_type,omitempty"`
	FoodDrinks             string        `protobuf:"bytes,18,opt,name=food_drinks,json=foodDrinks,proto3" json:"food_drinks,omitempty"`
	FreeMegazine           string        `protobuf:"bytes,19,opt,name=free_megazine,json=freeMegazine,proto3" json:"free_megazine,omitempty"`
	CleaningKit            string        `protobuf:"bytes,20,opt,name=cleaning_kit,json=cleaningKit,proto3" json:"cleaning_kit,omitempty"`
	WelcomeKit             string        `protobuf:"bytes,21,opt,name=welcome_kit,json=welcomeKit,proto3" json:"welcome_kit,omitempty"`
	LoungeService          string        `protobuf:"bytes,22,opt,name=lounge_service,json=loungeService,proto3" json:"lounge_service,omitempty"`
	CheckIn                string        `protobuf:"bytes,23,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	SilentArea             string        `protobuf:"bytes,24,opt,name=silent_area,json=silentArea,proto3" json:"silent_area,omitempty"`
	PrivateCabin           string        `protobuf:"bytes,25,opt,name=private_cabin,json=privateCabin,proto3" json:"private_cabin,omitempty"`
	PlayArea               string        `protobuf:"bytes,26,opt,name=play_area,json=playArea,proto3" json:"play_area,omitempty"`
	BicycleSpace           string        `protobuf:"bytes,27,opt,name=bicycle_space,json=bicycleSpace,proto3" json:"bicycle_space,omitempty"`
	DisabledFacilities     string        `protobuf:"bytes,28,opt,name=disabled_facilities,json=disabledFacilities,proto3" json:"disabled_facilities,omitempty"`
	MorningCall            string        `protobuf:"bytes,29,opt,name=morning_call,json=morningCall,proto3" json:"morning_call,omitempty"`
	HelpUrl                string        `protobuf:"bytes,30,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}      `json:"-"`
	XXX_unrecognized       []byte        `json:"-"`
	XXX_sizecache          int32         `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{11}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Service) GetAverageUnitPrice() *Price {
	if m != nil {
		return m.AverageUnitPrice
	}
	return nil
}

func (m *Service) GetAvailable() *Availability {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *Service) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Service) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Service) GetFeaturePhoto() string {
	if m != nil {
		return m.FeaturePhoto
	}
	return ""
}

func (m *Service) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *Service) GetBookingType() string {
	if m != nil {
		return m.BookingType
	}
	return ""
}

func (m *Service) GetHasWifi() string {
	if m != nil {
		return m.HasWifi
	}
	return ""
}

func (m *Service) GetHasPowerOutlet() string {
	if m != nil {
		return m.HasPowerOutlet
	}
	return ""
}

func (m *Service) GetHasAirConditioning() string {
	if m != nil {
		return m.HasAirConditioning
	}
	return ""
}

func (m *Service) GetHasEntertainmentSystem() string {
	if m != nil {
		return m.HasEntertainmentSystem
	}
	return ""
}

func (m *Service) GetHasReadingLight() string {
	if m != nil {
		return m.HasReadingLight
	}
	return ""
}

func (m *Service) GetSeatReservation() string {
	if m != nil {
		return m.SeatReservation
	}
	return ""
}

func (m *Service) GetSeatType() string {
	if m != nil {
		return m.SeatType
	}
	return ""
}

func (m *Service) GetNumberOfSeatsPerRow() string {
	if m != nil {
		return m.NumberOfSeatsPerRow
	}
	return ""
}

func (m *Service) GetBedType() string {
	if m != nil {
		return m.BedType
	}
	return ""
}

func (m *Service) GetToiletType() string {
	if m != nil {
		return m.ToiletType
	}
	return ""
}

func (m *Service) GetFoodServiceType() string {
	if m != nil {
		return m.FoodServiceType
	}
	return ""
}

func (m *Service) GetFoodDrinks() string {
	if m != nil {
		return m.FoodDrinks
	}
	return ""
}

func (m *Service) GetFreeMegazine() string {
	if m != nil {
		return m.FreeMegazine
	}
	return ""
}

func (m *Service) GetCleaningKit() string {
	if m != nil {
		return m.CleaningKit
	}
	return ""
}

func (m *Service) GetWelcomeKit() string {
	if m != nil {
		return m.WelcomeKit
	}
	return ""
}

func (m *Service) GetLoungeService() string {
	if m != nil {
		return m.LoungeService
	}
	return ""
}

func (m *Service) GetCheckIn() string {
	if m != nil {
		return m.CheckIn
	}
	return ""
}

func (m *Service) GetSilentArea() string {
	if m != nil {
		return m.SilentArea
	}
	return ""
}

func (m *Service) GetPrivateCabin() string {
	if m != nil {
		return m.PrivateCabin
	}
	return ""
}

func (m *Service) GetPlayArea() string {
	if m != nil {
		return m.PlayArea
	}
	return ""
}

func (m *Service) GetBicycleSpace() string {
	if m != nil {
		return m.BicycleSpace
	}
	return ""
}

func (m *Service) GetDisabledFacilities() string {
	if m != nil {
		return m.DisabledFacilities
	}
	return ""
}

func (m *Service) GetMorningCall() string {
	if m != nil {
		return m.MorningCall
	}
	return ""
}

func (m *Service) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

type Availability struct {
	Seats                uint32   `protobuf:"varint,1,opt,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Availability) Reset()         { *m = Availability{} }
func (m *Availability) String() string { return proto.CompactTextString(m) }
func (*Availability) ProtoMessage()    {}
func (*Availability) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{12}
}

func (m *Availability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Availability.Unmarshal(m, b)
}
func (m *Availability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Availability.Marshal(b, m, deterministic)
}
func (m *Availability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Availability.Merge(m, src)
}
func (m *Availability) XXX_Size() int {
	return xxx_messageInfo_Availability.Size(m)
}
func (m *Availability) XXX_DiscardUnknown() {
	xxx_messageInfo_Availability.DiscardUnknown(m)
}

var xxx_messageInfo_Availability proto.InternalMessageInfo

func (m *Availability) GetSeats() uint32 {
	if m != nil {
		return m.Seats
	}
	return 0
}

type Price struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Cents                uint32   `protobuf:"varint,2,opt,name=cents,proto3" json:"cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{13}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetCents() uint32 {
	if m != nil {
		return m.Cents
	}
	return 0
}

type Train struct {
	From                 *Station `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	HelpUrl              string   `protobuf:"bytes,5,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	Departure            string   `protobuf:"bytes,6,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              string   `protobuf:"bytes,7,opt,name=arrival,proto3" json:"arrival,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Train) Reset()         { *m = Train{} }
func (m *Train) String() string { return proto.CompactTextString(m) }
func (*Train) ProtoMessage()    {}
func (*Train) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6ae3b476437f88, []int{14}
}

func (m *Train) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Train.Unmarshal(m, b)
}
func (m *Train) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Train.Marshal(b, m, deterministic)
}
func (m *Train) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Train.Merge(m, src)
}
func (m *Train) XXX_Size() int {
	return xxx_messageInfo_Train.Size(m)
}
func (m *Train) XXX_DiscardUnknown() {
	xxx_messageInfo_Train.DiscardUnknown(m)
}

var xxx_messageInfo_Train proto.InternalMessageInfo

func (m *Train) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Train) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Train) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Train) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Train) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

func (m *Train) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Train) GetArrival() string {
	if m != nil {
		return m.Arrival
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "g2rail.SearchRequest")
	proto.RegisterType((*AsyncKeyResponse)(nil), "g2rail.AsyncKeyResponse")
	proto.RegisterType((*OnlineSolutionsAsyncQueryRequest)(nil), "g2rail.OnlineSolutionsAsyncQueryRequest")
	proto.RegisterType((*OnlineSolutionsResponse)(nil), "g2rail.OnlineSolutionsResponse")
	proto.RegisterType((*RailwaySolution)(nil), "g2rail.RailwaySolution")
	proto.RegisterType((*Railway)(nil), "g2rail.Railway")
	proto.RegisterType((*Station)(nil), "g2rail.Station")
	proto.RegisterType((*Duration)(nil), "g2rail.Duration")
	proto.RegisterType((*Solution)(nil), "g2rail.Solution")
	proto.RegisterType((*Section)(nil), "g2rail.Section")
	proto.RegisterType((*Offer)(nil), "g2rail.Offer")
	proto.RegisterType((*Service)(nil), "g2rail.Service")
	proto.RegisterType((*Availability)(nil), "g2rail.Availability")
	proto.RegisterType((*Price)(nil), "g2rail.Price")
	proto.RegisterType((*Train)(nil), "g2rail.Train")
}

func init() { proto.RegisterFile("OnlineSolutions.proto", fileDescriptor_1f6ae3b476437f88) }

var fileDescriptor_1f6ae3b476437f88 = []byte{
	// 1411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x6e, 0x1c, 0x45,
	0x13, 0xd6, 0x3a, 0xde, 0x53, 0xdb, 0xeb, 0x43, 0xc7, 0xb1, 0xdb, 0x4e, 0xf2, 0xdb, 0x59, 0xff,
	0x91, 0x9c, 0x80, 0x9c, 0xc8, 0x70, 0x91, 0x88, 0x0b, 0xe4, 0xd8, 0x20, 0x45, 0x09, 0xb2, 0x19,
	0x27, 0x42, 0xe2, 0x66, 0xd4, 0x3b, 0x53, 0xbb, 0xdb, 0xf2, 0x6c, 0xf7, 0xd2, 0xdd, 0x63, 0x6b,
	0x79, 0x00, 0x78, 0x21, 0x1e, 0x03, 0xf1, 0x08, 0x5c, 0xf1, 0x00, 0x3c, 0x02, 0xaa, 0x3e, 0xcc,
	0x1e, 0x08, 0x70, 0x93, 0xbb, 0xe9, 0xaf, 0xbe, 0xae, 0xa9, 0xae, 0xfe, 0xaa, 0xa6, 0x86, 0xdc,
	0xbb, 0x90, 0x85, 0x90, 0x70, 0xa5, 0x8a, 0xd2, 0x0a, 0x25, 0xcd, 0xf1, 0x58, 0x2b, 0xab, 0x68,
	0x63, 0x70, 0xa2, 0xb9, 0x28, 0xba, 0x3f, 0xd7, 0x48, 0xe7, 0x0a, 0xb8, 0xce, 0x86, 0x09, 0xfc,
	0x50, 0x82, 0xb1, 0x94, 0x92, 0xe5, 0xbe, 0x56, 0x23, 0x56, 0x3b, 0xa8, 0x1d, 0xb5, 0x13, 0xf7,
	0x4c, 0xd7, 0xc8, 0x92, 0x55, 0x6c, 0xc9, 0x21, 0x4b, 0x56, 0x21, 0x27, 0xe7, 0x16, 0xd8, 0x1d,
	0xcf, 0xc1, 0x67, 0xc4, 0xac, 0x18, 0x01, 0x5b, 0xf6, 0x18, 0x3e, 0xd3, 0x2d, 0x52, 0xe7, 0x79,
	0x59, 0x58, 0x56, 0x3f, 0xa8, 0x1d, 0x75, 0x12, 0xbf, 0x40, 0x34, 0x1b, 0x8a, 0x22, 0x67, 0x0d,
	0x8f, 0xba, 0x45, 0xf7, 0x19, 0xd9, 0x38, 0x35, 0x13, 0x99, 0xbd, 0x81, 0x49, 0x02, 0x66, 0xac,
	0xa4, 0x01, 0x7a, 0x9f, 0xb4, 0x39, 0x62, 0xe9, 0x35, 0x4c, 0x42, 0x40, 0x2d, 0x1e, 0x48, 0xdd,
	0x2f, 0xc9, 0xc1, 0xc2, 0xd9, 0xdc, 0xfe, 0x6f, 0x4b, 0xd0, 0x93, 0x78, 0x98, 0x7f, 0x75, 0x90,
	0x92, 0x9d, 0x05, 0x07, 0xd5, 0x8b, 0xcf, 0xc9, 0x26, 0xa6, 0xe7, 0x96, 0x4f, 0x52, 0x13, 0x8d,
	0xac, 0x76, 0x70, 0xe7, 0x68, 0xe5, 0x64, 0xe7, 0xd8, 0xa7, 0xee, 0x38, 0xf1, 0x84, 0xb8, 0x39,
	0xd9, 0xd0, 0xf3, 0x80, 0xe9, 0xfe, 0x54, 0x23, 0xeb, 0x0b, 0x2c, 0xfa, 0x84, 0x34, 0x03, 0xcf,
	0xc5, 0xb3, 0x72, 0xb2, 0xbe, 0xe0, 0x2f, 0x89, 0x76, 0xca, 0x48, 0xb3, 0x50, 0x3c, 0x17, 0x72,
	0xe0, 0x52, 0xdf, 0x4a, 0xe2, 0x92, 0x1e, 0x93, 0xf6, 0x34, 0xac, 0x3b, 0x2e, 0xac, 0x8d, 0xe8,
	0xa6, 0x8a, 0x67, 0x4a, 0xe9, 0x3e, 0x24, 0xcd, 0xe0, 0x1d, 0xaf, 0x29, 0x53, 0x39, 0xc4, 0xeb,
	0xc5, 0xe7, 0xee, 0x5b, 0xd2, 0xbc, 0xb2, 0xdc, 0x85, 0x47, 0xc9, 0xb2, 0xe4, 0xa3, 0xca, 0x8c,
	0xcf, 0xd5, 0x96, 0xa5, 0xe9, 0x16, 0xba, 0x4b, 0x5a, 0x43, 0x28, 0xc6, 0x69, 0xa9, 0x8b, 0xa0,
	0x82, 0x26, 0xae, 0xdf, 0xeb, 0xa2, 0xfb, 0x82, 0xb4, 0xce, 0x4b, 0x5d, 0xb9, 0x1b, 0xaa, 0x52,
	0x3b, 0x77, 0x9d, 0xc4, 0x3d, 0xe3, 0xb1, 0x46, 0x42, 0x96, 0x16, 0x8c, 0xf3, 0xd8, 0x49, 0xe2,
	0xb2, 0xfb, 0x67, 0x8d, 0xb4, 0xaa, 0x44, 0x1d, 0xce, 0xe8, 0x70, 0x26, 0x4b, 0x21, 0xd0, 0x20,
	0xcc, 0xfd, 0x4a, 0x98, 0x1f, 0xa0, 0xa0, 0x52, 0x1f, 0x90, 0x76, 0x0e, 0x63, 0xae, 0x6d, 0xa9,
	0xa3, 0x5c, 0xa7, 0x00, 0x7d, 0x4c, 0xd6, 0xac, 0xe6, 0xd2, 0xf4, 0x41, 0xa7, 0x28, 0x58, 0xe3,
	0xd4, 0xdb, 0x49, 0x3a, 0x11, 0x7d, 0x87, 0x20, 0xfd, 0x94, 0xb4, 0xf2, 0x70, 0x22, 0xa7, 0xe4,
	0x99, 0x6c, 0xc7, 0x93, 0x26, 0x15, 0x83, 0x7e, 0x42, 0x5a, 0x06, 0x32, 0x7f, 0x37, 0x0d, 0x77,
	0x37, 0xd3, 0xc8, 0x3c, 0x9e, 0x54, 0x84, 0xee, 0x6f, 0x35, 0xd2, 0x0c, 0x28, 0x7d, 0x44, 0x56,
	0x33, 0xae, 0xb5, 0x00, 0x9d, 0xce, 0x5c, 0xd1, 0x4a, 0xc0, 0xce, 0x30, 0xed, 0xcf, 0xc8, 0xdd,
	0x48, 0xc9, 0xc1, 0x64, 0x5a, 0x8c, 0x5d, 0x50, 0xfe, 0x66, 0x68, 0x30, 0x9d, 0x4f, 0x2d, 0xb3,
	0x3e, 0x45, 0xa6, 0x64, 0x48, 0x41, 0xf4, 0xf9, 0x3a, 0x53, 0x92, 0x3e, 0x26, 0x0d, 0xd5, 0xef,
	0x83, 0xc6, 0xc3, 0x63, 0xb4, 0x9d, 0x18, 0xed, 0x05, 0xa2, 0x49, 0x30, 0x22, 0xcd, 0x6a, 0x2e,
	0xa4, 0x61, 0xf5, 0x79, 0xda, 0x3b, 0x44, 0x93, 0x60, 0xec, 0xfe, 0xb1, 0x44, 0xea, 0x6e, 0xe3,
	0x87, 0x94, 0x46, 0x0f, 0xc8, 0xca, 0xdf, 0xe3, 0x9e, 0x85, 0xe8, 0x36, 0x69, 0xe4, 0x60, 0xb9,
	0x88, 0xb2, 0x0a, 0xab, 0x39, 0xc1, 0x2d, 0xcf, 0x09, 0x0e, 0x9d, 0x6a, 0x30, 0x56, 0x8b, 0xac,
	0xba, 0xa1, 0x76, 0x32, 0x0b, 0xd1, 0x7d, 0xb2, 0x62, 0x45, 0x76, 0x0d, 0x36, 0xb5, 0x93, 0x31,
	0xb8, 0xbe, 0xd3, 0x4e, 0x88, 0x87, 0xde, 0x4d, 0xc6, 0xae, 0xd1, 0x18, 0xe0, 0xc1, 0xdc, 0xf4,
	0x7d, 0x02, 0x01, 0x67, 0xdc, 0x47, 0xff, 0xfd, 0x52, 0xe6, 0xde, 0xdc, 0xf2, 0xbb, 0x3d, 0xe4,
	0x08, 0x87, 0xa4, 0x93, 0x29, 0xd9, 0x17, 0x7a, 0x94, 0xf2, 0x01, 0x17, 0x92, 0xb5, 0x1d, 0x65,
	0x35, 0x80, 0xa7, 0x88, 0xa1, 0x97, 0x6c, 0xc8, 0xe5, 0x00, 0xbc, 0x17, 0xe2, 0xbd, 0x78, 0xc8,
	0x79, 0x71, 0xba, 0xd1, 0x37, 0x22, 0x03, 0xc3, 0x56, 0x16, 0x75, 0xe3, 0xf0, 0xa4, 0x22, 0x74,
	0x7f, 0x6f, 0xa3, 0x6e, 0xdc, 0x82, 0x1e, 0x92, 0xfa, 0x58, 0x8b, 0x0c, 0xd8, 0xbe, 0xd3, 0x66,
	0x75, 0x31, 0x97, 0x08, 0x26, 0xde, 0x46, 0xbf, 0x20, 0x94, 0xdf, 0x80, 0xe6, 0x03, 0x48, 0x4b,
	0x29, 0x6c, 0xea, 0x77, 0x1c, 0x7c, 0x68, 0xc7, 0x46, 0x20, 0xbe, 0x97, 0xc2, 0x3a, 0x84, 0x9e,
	0x90, 0x36, 0xbf, 0xe1, 0xa2, 0xe0, 0xbd, 0x02, 0xd8, 0x23, 0xb7, 0x67, 0x2b, 0xee, 0x39, 0xf5,
	0x06, 0x51, 0x08, 0x3b, 0x49, 0xa6, 0xb4, 0x8f, 0x7c, 0xfd, 0x87, 0xa4, 0xd3, 0x07, 0x8e, 0x45,
	0x9b, 0x8e, 0x87, 0xca, 0xaa, 0xa0, 0x81, 0xd5, 0x00, 0x5e, 0x22, 0x86, 0x62, 0xef, 0x29, 0x75,
	0x2d, 0xe4, 0xc0, 0x17, 0x50, 0x50, 0x42, 0xc0, 0x5c, 0x01, 0xcd, 0x50, 0x66, 0xa4, 0x10, 0x29,
	0xee, 0x1e, 0x50, 0x69, 0xdc, 0xa4, 0xb7, 0xa2, 0x2f, 0x82, 0x14, 0x9a, 0x43, 0x6e, 0xbe, 0x13,
	0x7d, 0x41, 0x8f, 0xc8, 0x06, 0x9a, 0xc6, 0xea, 0x16, 0x74, 0xaa, 0x4a, 0x5b, 0x80, 0x0d, 0x72,
	0x58, 0x1b, 0x72, 0x73, 0x89, 0xf0, 0x85, 0x43, 0xe9, 0x73, 0xb2, 0x85, 0x4c, 0x2e, 0xb0, 0x96,
	0x65, 0x2e, 0xf0, 0x70, 0xd8, 0xc8, 0xbd, 0x32, 0xe8, 0x90, 0x9b, 0x53, 0xa1, 0xcf, 0x66, 0x2c,
	0xf4, 0x05, 0x61, 0xb8, 0x03, 0xa4, 0x05, 0x6d, 0xb9, 0x90, 0x23, 0x90, 0x36, 0x35, 0x13, 0x63,
	0x61, 0x14, 0xc4, 0xb2, 0x3d, 0xe4, 0xe6, 0xab, 0x59, 0xf3, 0x95, 0xb3, 0xd2, 0xa7, 0x64, 0x13,
	0x77, 0x6a, 0x70, 0x1f, 0x87, 0xb4, 0x10, 0x83, 0xa1, 0x65, 0x2b, 0x6e, 0xcb, 0xfa, 0x90, 0x9b,
	0xc4, 0xe3, 0x6f, 0x11, 0xa6, 0x4f, 0xc8, 0x86, 0x13, 0xba, 0x06, 0x94, 0x92, 0x6f, 0x69, 0xab,
	0x9e, 0x8a, 0x78, 0x32, 0x85, 0xe7, 0x6b, 0xa2, 0xb3, 0x50, 0x13, 0x9f, 0x93, 0x1d, 0x59, 0x8e,
	0x7a, 0x98, 0x86, 0x7e, 0x8a, 0xa8, 0x49, 0xc7, 0xa0, 0x53, 0xad, 0x6e, 0xd9, 0x9a, 0xa3, 0xde,
	0xf5, 0xe6, 0x8b, 0xfe, 0x15, 0x1a, 0x2f, 0x41, 0x27, 0xea, 0x16, 0x53, 0xdb, 0x83, 0x50, 0x46,
	0xeb, 0x3e, 0xb5, 0x3d, 0xc8, 0x63, 0x91, 0x59, 0x25, 0x8a, 0x58, 0xa2, 0x1b, 0xa1, 0x44, 0x1d,
	0xe4, 0x08, 0x4f, 0xc9, 0x66, 0x5f, 0xa9, 0x3c, 0x0d, 0x25, 0xe0, 0x69, 0x9b, 0x3e, 0x74, 0x34,
	0x84, 0x6a, 0x88, 0xce, 0x1c, 0x37, 0xd7, 0x42, 0x5e, 0x1b, 0x46, 0xbd, 0x33, 0x84, 0xce, 0x1d,
	0xe2, 0xe4, 0xa4, 0x01, 0xd2, 0x11, 0x0c, 0xf8, 0x8f, 0x42, 0x02, 0xbb, 0x1b, 0xe4, 0xa4, 0x01,
	0xbe, 0x09, 0x98, 0xeb, 0x9d, 0x05, 0x70, 0xbc, 0x9d, 0xf4, 0x5a, 0x58, 0xb6, 0x15, 0x7a, 0x67,
	0xc0, 0xde, 0x08, 0x8b, 0x2f, 0xba, 0x85, 0x22, 0x53, 0x23, 0x70, 0x8c, 0x7b, 0xfe, 0x45, 0x01,
	0x42, 0xc2, 0x63, 0xb2, 0x56, 0xa8, 0x12, 0xab, 0x3e, 0xc4, 0xcd, 0xb6, 0x1d, 0xa7, 0xe3, 0xd1,
	0x58, 0xc2, 0xbb, 0xa4, 0x95, 0x0d, 0x21, 0xbb, 0x4e, 0x85, 0x64, 0x3b, 0x3e, 0x31, 0x6e, 0xfd,
	0xda, 0xf5, 0x0d, 0x23, 0x0a, 0x14, 0x03, 0xd7, 0xc0, 0x19, 0xf3, 0xaf, 0xf0, 0xd0, 0xa9, 0x06,
	0x8e, 0x67, 0x19, 0x6b, 0x71, 0xc3, 0x2d, 0xa4, 0x19, 0xef, 0x09, 0xc9, 0x76, 0xfd, 0x59, 0x02,
	0x78, 0x86, 0x18, 0x5e, 0xe6, 0xb8, 0xe0, 0x13, 0xef, 0x63, 0xcf, 0x5f, 0x26, 0x02, 0xd1, 0x43,
	0x4f, 0x64, 0x93, 0xac, 0x80, 0xd4, 0x8c, 0x79, 0x06, 0xec, 0xbe, 0xf7, 0x10, 0xc0, 0x2b, 0xc4,
	0xf0, 0xd3, 0x93, 0x0b, 0x83, 0xa5, 0x9d, 0xa7, 0x7d, 0x9e, 0x61, 0xbd, 0x0b, 0x30, 0xec, 0x81,
	0x17, 0x74, 0x34, 0x7d, 0x5d, 0x59, 0x30, 0x7d, 0x23, 0xa5, 0x5d, 0xf6, 0x32, 0x5e, 0x14, 0xec,
	0xa1, 0x4f, 0x5f, 0xc0, 0xce, 0x78, 0x31, 0xdf, 0xd4, 0xff, 0x37, 0x3f, 0x45, 0xfc, 0x9f, 0xac,
	0xce, 0x76, 0x16, 0x1c, 0x1a, 0x9d, 0xcc, 0xc2, 0x28, 0xe1, 0x17, 0xdd, 0x97, 0xa4, 0xee, 0x3b,
	0xd4, 0x1e, 0x69, 0x65, 0xa5, 0xd6, 0x20, 0xb3, 0x6a, 0xce, 0x8b, 0x6b, 0x37, 0x6f, 0x82, 0xb4,
	0x71, 0xdc, 0xf0, 0x8b, 0xee, 0xaf, 0x35, 0x52, 0x77, 0x9f, 0xae, 0x8f, 0x34, 0x69, 0x6c, 0x93,
	0x86, 0x97, 0x7c, 0xec, 0x5c, 0x7e, 0xe5, 0xe6, 0x62, 0x94, 0x6a, 0x9c, 0x8b, 0x63, 0x8b, 0x89,
	0xe7, 0xae, 0xcf, 0x7f, 0xcc, 0xe6, 0x06, 0x96, 0xc6, 0xe2, 0xc0, 0xc2, 0x48, 0x13, 0xbf, 0xdc,
	0x37, 0xbc, 0x88, 0xad, 0x29, 0x2c, 0x4f, 0x7e, 0xa9, 0x91, 0xf5, 0x85, 0x69, 0x96, 0xbe, 0x24,
	0x0d, 0x3f, 0xdb, 0xd3, 0x7b, 0xd3, 0x2f, 0xc9, 0xcc, 0xac, 0xbf, 0xc7, 0xaa, 0x26, 0xbe, 0x38,
	0x79, 0xf7, 0xc9, 0xae, 0x1b, 0xa4, 0x9d, 0x61, 0xd1, 0xef, 0x51, 0x35, 0x21, 0xfc, 0xc7, 0xfc,
	0xbd, 0xb7, 0xff, 0x0f, 0xcc, 0xf8, 0x9e, 0x57, 0xcf, 0xc9, 0x9a, 0x50, 0xc7, 0x03, 0x3d, 0xce,
	0x02, 0xf3, 0xd5, 0xd6, 0x02, 0xf5, 0x12, 0xff, 0x57, 0x2e, 0x6b, 0xdf, 0x87, 0x3f, 0x96, 0x5e,
	0xc3, 0xfd, 0xc0, 0x7c, 0xf6, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0xe2, 0x81, 0x41, 0xd9,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlineSolutionsClient is the client API for OnlineSolutions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlineSolutionsClient interface {
	// Send a search request
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineSolutions(ctx context.Context, in *OnlineSolutionsAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineSolutionsResponse, error)
}

type onlineSolutionsClient struct {
	cc *grpc.ClientConn
}

func NewOnlineSolutionsClient(cc *grpc.ClientConn) OnlineSolutionsClient {
	return &onlineSolutionsClient{cc}
}

func (c *onlineSolutionsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error) {
	out := new(AsyncKeyResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineSolutions/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineSolutionsClient) QueryAsyncOnlineSolutions(ctx context.Context, in *OnlineSolutionsAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineSolutionsResponse, error) {
	out := new(OnlineSolutionsResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineSolutions/QueryAsyncOnlineSolutions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineSolutionsServer is the server API for OnlineSolutions service.
type OnlineSolutionsServer interface {
	// Send a search request
	Search(context.Context, *SearchRequest) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineSolutions(context.Context, *OnlineSolutionsAsyncQueryRequest) (*OnlineSolutionsResponse, error)
}

func RegisterOnlineSolutionsServer(s *grpc.Server, srv OnlineSolutionsServer) {
	s.RegisterService(&_OnlineSolutions_serviceDesc, srv)
}

func _OnlineSolutions_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineSolutionsServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineSolutions/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineSolutionsServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineSolutions_QueryAsyncOnlineSolutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineSolutionsAsyncQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineSolutionsServer).QueryAsyncOnlineSolutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineSolutions/QueryAsyncOnlineSolutions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineSolutionsServer).QueryAsyncOnlineSolutions(ctx, req.(*OnlineSolutionsAsyncQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlineSolutions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.OnlineSolutions",
	HandlerType: (*OnlineSolutionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _OnlineSolutions_Search_Handler,
		},
		{
			MethodName: "QueryAsyncOnlineSolutions",
			Handler:    _OnlineSolutions_QueryAsyncOnlineSolutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "OnlineSolutions.proto",
}
