// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/Common.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Passenger_Gender int32

const (
	Passenger_male   Passenger_Gender = 0
	Passenger_female Passenger_Gender = 1
)

var Passenger_Gender_name = map[int32]string{
	0: "male",
	1: "female",
}

var Passenger_Gender_value = map[string]int32{
	"male":   0,
	"female": 1,
}

func (x Passenger_Gender) String() string {
	return proto.EnumName(Passenger_Gender_name, int32(x))
}

func (Passenger_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{7, 0}
}

type Railway struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Railway) Reset()         { *m = Railway{} }
func (m *Railway) String() string { return proto.CompactTextString(m) }
func (*Railway) ProtoMessage()    {}
func (*Railway) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{0}
}

func (m *Railway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Railway.Unmarshal(m, b)
}
func (m *Railway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Railway.Marshal(b, m, deterministic)
}
func (m *Railway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Railway.Merge(m, src)
}
func (m *Railway) XXX_Size() int {
	return xxx_messageInfo_Railway.Size(m)
}
func (m *Railway) XXX_DiscardUnknown() {
	xxx_messageInfo_Railway.DiscardUnknown(m)
}

var xxx_messageInfo_Railway proto.InternalMessageInfo

func (m *Railway) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Station struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	HelpUrl              string   `protobuf:"bytes,3,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{1}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Station) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

type Price struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Cents                uint32   `protobuf:"varint,2,opt,name=cents,proto3" json:"cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{2}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetCents() uint32 {
	if m != nil {
		return m.Cents
	}
	return 0
}

type AsyncKeyResponse struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncKeyResponse) Reset()         { *m = AsyncKeyResponse{} }
func (m *AsyncKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncKeyResponse) ProtoMessage()    {}
func (*AsyncKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{3}
}

func (m *AsyncKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncKeyResponse.Unmarshal(m, b)
}
func (m *AsyncKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncKeyResponse.Marshal(b, m, deterministic)
}
func (m *AsyncKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncKeyResponse.Merge(m, src)
}
func (m *AsyncKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AsyncKeyResponse.Size(m)
}
func (m *AsyncKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncKeyResponse proto.InternalMessageInfo

func (m *AsyncKeyResponse) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type Train struct {
	From                 *Station `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	HelpUrl              string   `protobuf:"bytes,5,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	Departure            string   `protobuf:"bytes,6,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              string   `protobuf:"bytes,7,opt,name=arrival,proto3" json:"arrival,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Train) Reset()         { *m = Train{} }
func (m *Train) String() string { return proto.CompactTextString(m) }
func (*Train) ProtoMessage()    {}
func (*Train) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{4}
}

func (m *Train) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Train.Unmarshal(m, b)
}
func (m *Train) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Train.Marshal(b, m, deterministic)
}
func (m *Train) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Train.Merge(m, src)
}
func (m *Train) XXX_Size() int {
	return xxx_messageInfo_Train.Size(m)
}
func (m *Train) XXX_DiscardUnknown() {
	xxx_messageInfo_Train.DiscardUnknown(m)
}

var xxx_messageInfo_Train proto.InternalMessageInfo

func (m *Train) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Train) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Train) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Train) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Train) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

func (m *Train) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Train) GetArrival() string {
	if m != nil {
		return m.Arrival
	}
	return ""
}

type Ticket struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 *Station `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Price                *Price   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{5}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Ticket) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Ticket) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type PriceDetail struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               *Price   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Target               string   `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceDetail) Reset()         { *m = PriceDetail{} }
func (m *PriceDetail) String() string { return proto.CompactTextString(m) }
func (*PriceDetail) ProtoMessage()    {}
func (*PriceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{6}
}

func (m *PriceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceDetail.Unmarshal(m, b)
}
func (m *PriceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceDetail.Marshal(b, m, deterministic)
}
func (m *PriceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceDetail.Merge(m, src)
}
func (m *PriceDetail) XXX_Size() int {
	return xxx_messageInfo_PriceDetail.Size(m)
}
func (m *PriceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PriceDetail proto.InternalMessageInfo

func (m *PriceDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PriceDetail) GetAmount() *Price {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *PriceDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PriceDetail) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PriceDetail) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type Passenger struct {
	Gender               Passenger_Gender `protobuf:"varint,1,opt,name=gender,proto3,enum=g2rail.Passenger_Gender" json:"gender,omitempty"`
	Id                   string           `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string           `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	LastName             string           `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstName            string           `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Birthdate            string           `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string           `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Passport             string           `protobuf:"bytes,7,opt,name=passport,proto3" json:"passport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Passenger) Reset()         { *m = Passenger{} }
func (m *Passenger) String() string { return proto.CompactTextString(m) }
func (*Passenger) ProtoMessage()    {}
func (*Passenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{7}
}

func (m *Passenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passenger.Unmarshal(m, b)
}
func (m *Passenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passenger.Marshal(b, m, deterministic)
}
func (m *Passenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passenger.Merge(m, src)
}
func (m *Passenger) XXX_Size() int {
	return xxx_messageInfo_Passenger.Size(m)
}
func (m *Passenger) XXX_DiscardUnknown() {
	xxx_messageInfo_Passenger.DiscardUnknown(m)
}

var xxx_messageInfo_Passenger proto.InternalMessageInfo

func (m *Passenger) GetGender() Passenger_Gender {
	if m != nil {
		return m.Gender
	}
	return Passenger_male
}

func (m *Passenger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Passenger) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Passenger) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Passenger) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Passenger) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *Passenger) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Passenger) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func init() {
	proto.RegisterEnum("g2rail.Passenger_Gender", Passenger_Gender_name, Passenger_Gender_value)
	proto.RegisterType((*Railway)(nil), "g2rail.Railway")
	proto.RegisterType((*Station)(nil), "g2rail.Station")
	proto.RegisterType((*Price)(nil), "g2rail.Price")
	proto.RegisterType((*AsyncKeyResponse)(nil), "g2rail.AsyncKeyResponse")
	proto.RegisterType((*Train)(nil), "g2rail.Train")
	proto.RegisterType((*Ticket)(nil), "g2rail.Ticket")
	proto.RegisterType((*PriceDetail)(nil), "g2rail.PriceDetail")
	proto.RegisterType((*Passenger)(nil), "g2rail.Passenger")
}

func init() { proto.RegisterFile("lib/proto/Common.proto", fileDescriptor_2672edadb2f5b2ae) }

var fileDescriptor_2672edadb2f5b2ae = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0xd9, 0x8d, 0x9d, 0x78, 0xa2, 0xa6, 0xfd, 0xad, 0xaa, 0xca, 0x40, 0x0b, 0xc8, 0x15,
	0x12, 0x27, 0x07, 0x85, 0x13, 0x27, 0x44, 0x41, 0xea, 0x01, 0x84, 0x22, 0x53, 0x2e, 0x5c, 0xa2,
	0x8d, 0x3d, 0x71, 0x56, 0xb5, 0x77, 0xad, 0xf5, 0x1a, 0xe4, 0x33, 0x57, 0x24, 0xbe, 0x07, 0x9f,
	0x85, 0x0f, 0x85, 0xf6, 0x4f, 0x1c, 0xca, 0x1f, 0x71, 0xdb, 0x37, 0x6f, 0x76, 0x76, 0xde, 0xf3,
	0x8c, 0xe1, 0xb4, 0x62, 0xeb, 0x79, 0x23, 0x85, 0x12, 0xf3, 0x97, 0xa2, 0xae, 0x05, 0x4f, 0x0d,
	0x20, 0x61, 0xb9, 0x90, 0x94, 0x55, 0xc9, 0x39, 0x8c, 0x33, 0xca, 0xaa, 0x4f, 0xb4, 0x27, 0x04,
	0x46, 0xb9, 0x28, 0x30, 0xf6, 0x1e, 0x7a, 0x8f, 0xa3, 0xcc, 0x9c, 0x93, 0x37, 0x30, 0x7e, 0xa7,
	0xa8, 0x62, 0x82, 0x6b, 0x9a, 0xd3, 0x7a, 0xa0, 0xf5, 0x79, 0xb8, 0xe2, 0xef, 0xaf, 0x90, 0x3b,
	0x30, 0xd9, 0x62, 0xd5, 0xac, 0x3a, 0x59, 0xc5, 0x07, 0x26, 0x3e, 0xd6, 0xf8, 0xbd, 0xac, 0x92,
	0x67, 0x10, 0x2c, 0x25, 0xcb, 0x91, 0xdc, 0x85, 0x49, 0xde, 0x49, 0x89, 0x3c, 0xef, 0x5d, 0xbd,
	0x01, 0x93, 0x13, 0x08, 0x72, 0xe4, 0xaa, 0x35, 0x45, 0x0f, 0x33, 0x0b, 0x92, 0x39, 0x1c, 0xbf,
	0x68, 0x7b, 0x9e, 0xbf, 0xc6, 0x3e, 0xc3, 0xb6, 0x11, 0xbc, 0x45, 0x72, 0x0f, 0x22, 0xaa, 0x63,
	0xab, 0x1b, 0x1c, 0xca, 0x50, 0x97, 0x94, 0x7c, 0xf7, 0x20, 0xb8, 0x96, 0x94, 0x71, 0x72, 0x01,
	0xa3, 0x8d, 0x14, 0xb5, 0xc9, 0x98, 0x2e, 0x8e, 0x52, 0xab, 0x3c, 0x75, 0xba, 0x32, 0x43, 0x92,
	0x07, 0xe0, 0x2b, 0x61, 0x9e, 0xfc, 0x43, 0x8a, 0xaf, 0x04, 0x39, 0x85, 0x90, 0x77, 0xf5, 0x1a,
	0xa5, 0x13, 0xe5, 0x90, 0xb6, 0x40, 0xf5, 0x0d, 0xc6, 0x23, 0x6b, 0x81, 0x3e, 0xdf, 0xb2, 0x20,
	0xb8, 0x65, 0x01, 0x39, 0x83, 0xa8, 0xc0, 0x86, 0x4a, 0xd5, 0x49, 0x8c, 0x43, 0xc3, 0xed, 0x03,
	0x24, 0x86, 0x31, 0x95, 0x92, 0x7d, 0xa4, 0x55, 0x3c, 0xb6, 0xf7, 0x1c, 0x4c, 0x3e, 0x7b, 0x10,
	0x5e, 0xb3, 0xfc, 0x06, 0x15, 0x99, 0x81, 0xcf, 0x0a, 0xa7, 0xd7, 0x67, 0xc5, 0xa0, 0xcf, 0xff,
	0xb7, 0xbe, 0x83, 0xbf, 0xeb, 0xbb, 0x80, 0xa0, 0xd1, 0xdf, 0xc6, 0x08, 0x99, 0x2e, 0x0e, 0x77,
	0x39, 0xe6, 0x83, 0x65, 0x96, 0x4b, 0xbe, 0x78, 0x30, 0x35, 0x81, 0x57, 0xa8, 0x28, 0xab, 0x7e,
	0x6b, 0xe5, 0x11, 0x84, 0xb4, 0x16, 0x1d, 0x57, 0xae, 0x99, 0x5f, 0xaa, 0x38, 0x72, 0xf0, 0xec,
	0xe0, 0x27, 0xcf, 0xf4, 0x48, 0x50, 0x85, 0xa5, 0x90, 0xbd, 0xf3, 0x72, 0xc0, 0xda, 0x7b, 0x45,
	0x65, 0x89, 0xca, 0xb9, 0xe9, 0x50, 0xf2, 0xd5, 0x87, 0x68, 0x49, 0xdb, 0x16, 0x79, 0x89, 0x92,
	0x3c, 0x81, 0xb0, 0x44, 0x5e, 0xa0, 0x34, 0x0d, 0xcd, 0x16, 0xf1, 0xf0, 0xf8, 0x2e, 0x25, 0xbd,
	0x32, 0x7c, 0xe6, 0xf2, 0x5c, 0xfb, 0x93, 0xa1, 0xfd, 0x13, 0x08, 0x9a, 0xad, 0xe0, 0xbb, 0x79,
	0xb6, 0x40, 0x8f, 0x59, 0x45, 0x5b, 0xb5, 0x32, 0xd3, 0x6f, 0x5b, 0x9e, 0xe8, 0xc0, 0x5b, 0xbd,
	0x01, 0xe7, 0x00, 0x1b, 0x26, 0x77, 0xac, 0x6d, 0x3c, 0x32, 0x11, 0x43, 0x9f, 0x41, 0xb4, 0x66,
	0x52, 0x6d, 0x0b, 0xaa, 0xd0, 0x35, 0xbf, 0x0f, 0xe8, 0xf7, 0xb0, 0xa6, 0xac, 0x72, 0x83, 0x60,
	0x81, 0x76, 0xa2, 0xa1, 0x6d, 0xdb, 0x08, 0xa9, 0xdc, 0x14, 0x0c, 0x38, 0xb9, 0x0f, 0xa1, 0xd5,
	0x40, 0x26, 0x30, 0xaa, 0x69, 0x85, 0xc7, 0xff, 0x11, 0x80, 0x70, 0x83, 0xe6, 0xec, 0x5d, 0x3e,
	0x87, 0x19, 0x13, 0x69, 0x29, 0x9b, 0xdc, 0x89, 0xbf, 0xfc, 0xff, 0x6a, 0xa1, 0x17, 0xdc, 0x2e,
	0xff, 0x52, 0xef, 0xfe, 0xd2, 0xfb, 0xe0, 0xb6, 0xff, 0x9b, 0x7f, 0x64, 0xd9, 0xd4, 0x10, 0xeb,
	0x6e, 0xb3, 0x0e, 0xcd, 0xef, 0xe1, 0xe9, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x49, 0xb5,
	0x58, 0x38, 0x04, 0x00, 0x00,
}
