// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/Common.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Railway struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Railway) Reset()         { *m = Railway{} }
func (m *Railway) String() string { return proto.CompactTextString(m) }
func (*Railway) ProtoMessage()    {}
func (*Railway) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{0}
}

func (m *Railway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Railway.Unmarshal(m, b)
}
func (m *Railway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Railway.Marshal(b, m, deterministic)
}
func (m *Railway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Railway.Merge(m, src)
}
func (m *Railway) XXX_Size() int {
	return xxx_messageInfo_Railway.Size(m)
}
func (m *Railway) XXX_DiscardUnknown() {
	xxx_messageInfo_Railway.DiscardUnknown(m)
}

var xxx_messageInfo_Railway proto.InternalMessageInfo

func (m *Railway) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Station struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	HelpUrl              string   `protobuf:"bytes,3,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{1}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Station) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

type Price struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Cents                uint32   `protobuf:"varint,2,opt,name=cents,proto3" json:"cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{2}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetCents() uint32 {
	if m != nil {
		return m.Cents
	}
	return 0
}

type AsyncKeyResponse struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncKeyResponse) Reset()         { *m = AsyncKeyResponse{} }
func (m *AsyncKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncKeyResponse) ProtoMessage()    {}
func (*AsyncKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{3}
}

func (m *AsyncKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncKeyResponse.Unmarshal(m, b)
}
func (m *AsyncKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncKeyResponse.Marshal(b, m, deterministic)
}
func (m *AsyncKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncKeyResponse.Merge(m, src)
}
func (m *AsyncKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AsyncKeyResponse.Size(m)
}
func (m *AsyncKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncKeyResponse proto.InternalMessageInfo

func (m *AsyncKeyResponse) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type Train struct {
	From                 *Station `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	HelpUrl              string   `protobuf:"bytes,5,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	Departure            string   `protobuf:"bytes,6,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              string   `protobuf:"bytes,7,opt,name=arrival,proto3" json:"arrival,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Train) Reset()         { *m = Train{} }
func (m *Train) String() string { return proto.CompactTextString(m) }
func (*Train) ProtoMessage()    {}
func (*Train) Descriptor() ([]byte, []int) {
	return fileDescriptor_2672edadb2f5b2ae, []int{4}
}

func (m *Train) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Train.Unmarshal(m, b)
}
func (m *Train) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Train.Marshal(b, m, deterministic)
}
func (m *Train) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Train.Merge(m, src)
}
func (m *Train) XXX_Size() int {
	return xxx_messageInfo_Train.Size(m)
}
func (m *Train) XXX_DiscardUnknown() {
	xxx_messageInfo_Train.DiscardUnknown(m)
}

var xxx_messageInfo_Train proto.InternalMessageInfo

func (m *Train) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Train) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Train) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Train) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Train) GetHelpUrl() string {
	if m != nil {
		return m.HelpUrl
	}
	return ""
}

func (m *Train) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Train) GetArrival() string {
	if m != nil {
		return m.Arrival
	}
	return ""
}

func init() {
	proto.RegisterType((*Railway)(nil), "g2rail.Railway")
	proto.RegisterType((*Station)(nil), "g2rail.Station")
	proto.RegisterType((*Price)(nil), "g2rail.Price")
	proto.RegisterType((*AsyncKeyResponse)(nil), "g2rail.AsyncKeyResponse")
	proto.RegisterType((*Train)(nil), "g2rail.Train")
}

func init() { proto.RegisterFile("lib/proto/Common.proto", fileDescriptor_2672edadb2f5b2ae) }

var fileDescriptor_2672edadb2f5b2ae = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4f, 0xeb, 0x30,
	0x10, 0x54, 0xf2, 0x9a, 0xa4, 0xdd, 0xa7, 0xf7, 0x0a, 0x16, 0xaa, 0xc2, 0x97, 0x40, 0xe1, 0xc2,
	0x29, 0x95, 0xca, 0x89, 0x13, 0xa2, 0x1c, 0x38, 0xc0, 0xa1, 0x0a, 0x70, 0xe1, 0x52, 0x39, 0xa9,
	0x5b, 0x2c, 0x1c, 0x3b, 0xda, 0x38, 0xa0, 0xfc, 0x25, 0x7e, 0x0b, 0x3f, 0x0a, 0xd9, 0xb1, 0x52,
	0x55, 0xe2, 0xb6, 0xb3, 0xb3, 0xbb, 0xf6, 0xcc, 0xc0, 0x44, 0xf0, 0x7c, 0x5a, 0xa1, 0xd2, 0x6a,
	0x7a, 0xa7, 0xca, 0x52, 0xc9, 0xd4, 0x02, 0x12, 0x6e, 0x66, 0x48, 0xb9, 0x48, 0x4e, 0x21, 0xca,
	0x28, 0x17, 0x9f, 0xb4, 0x25, 0x04, 0x06, 0x85, 0x5a, 0xb1, 0xd8, 0x3b, 0xf7, 0x2e, 0x47, 0x99,
	0xad, 0x93, 0x47, 0x88, 0x9e, 0x34, 0xd5, 0x5c, 0x49, 0x43, 0x4b, 0x5a, 0xf6, 0xb4, 0xa9, 0xfb,
	0x15, 0x7f, 0xbb, 0x42, 0x0e, 0x61, 0xf8, 0xc6, 0x44, 0xb5, 0x6c, 0x50, 0xc4, 0x7f, 0x6c, 0x3f,
	0x32, 0xf8, 0x05, 0x45, 0x72, 0x0d, 0xc1, 0x02, 0x79, 0xc1, 0xc8, 0x11, 0x0c, 0x8b, 0x06, 0x91,
	0xc9, 0xa2, 0x75, 0xf7, 0x7a, 0x4c, 0x0e, 0x20, 0x28, 0x98, 0xd4, 0xb5, 0x3d, 0xfa, 0x2f, 0xeb,
	0x40, 0x32, 0x85, 0xbd, 0xdb, 0xba, 0x95, 0xc5, 0x03, 0x6b, 0x33, 0x56, 0x57, 0x4a, 0xd6, 0x8c,
	0x1c, 0xc3, 0x88, 0x9a, 0xde, 0xf2, 0x9d, 0xf5, 0x67, 0xa8, 0x1b, 0x4a, 0xbe, 0x3d, 0x08, 0x9e,
	0x91, 0x72, 0x49, 0x2e, 0x60, 0xb0, 0x46, 0x55, 0xda, 0x89, 0xbf, 0xb3, 0x71, 0xda, 0x29, 0x4f,
	0x9d, 0xae, 0xcc, 0x92, 0xe4, 0x0c, 0x7c, 0xad, 0xec, 0x93, 0xbf, 0x8c, 0xf8, 0x5a, 0x91, 0x09,
	0x84, 0xb2, 0x29, 0x73, 0x86, 0x4e, 0x94, 0x43, 0xc6, 0x02, 0xdd, 0x56, 0x2c, 0x1e, 0x74, 0x16,
	0x98, 0x7a, 0xc7, 0x82, 0x60, 0xc7, 0x02, 0x72, 0x02, 0xa3, 0x15, 0xab, 0x28, 0xea, 0x06, 0x59,
	0x1c, 0x5a, 0x6e, 0xdb, 0x20, 0x31, 0x44, 0x14, 0x91, 0x7f, 0x50, 0x11, 0x47, 0xdd, 0x9e, 0x83,
	0xf3, 0x1b, 0xf8, 0xcf, 0x55, 0xba, 0xc1, 0xaa, 0x70, 0x9f, 0x9b, 0xef, 0xdf, 0xcf, 0x4c, 0x72,
	0x5d, 0xaa, 0x0b, 0x13, 0xea, 0xc2, 0x7b, 0x75, 0xb1, 0x7e, 0xf9, 0xe3, 0x8e, 0x4d, 0x2d, 0x91,
	0x37, 0xeb, 0x3c, 0xb4, 0xb9, 0x5f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x2e, 0x02, 0x3c,
	0x11, 0x02, 0x00, 0x00,
}
