// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/OnlineOrders.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Passenger_Gender int32

const (
	Passenger_male   Passenger_Gender = 0
	Passenger_female Passenger_Gender = 1
)

var Passenger_Gender_name = map[int32]string{
	0: "male",
	1: "female",
}

var Passenger_Gender_value = map[string]int32{
	"male":   0,
	"female": 1,
}

func (x Passenger_Gender) String() string {
	return proto.EnumName(Passenger_Gender_name, int32(x))
}

func (Passenger_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{1, 0}
}

type BookRequest struct {
	SeatReserved         bool         `protobuf:"varint,1,opt,name=seat_reserved,json=seatReserved,proto3" json:"seat_reserved,omitempty"`
	Sections             []string     `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Passengers           []*Passenger `protobuf:"bytes,3,rep,name=passengers,proto3" json:"passengers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{0}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetSeatReserved() bool {
	if m != nil {
		return m.SeatReserved
	}
	return false
}

func (m *BookRequest) GetSections() []string {
	if m != nil {
		return m.Sections
	}
	return nil
}

func (m *BookRequest) GetPassengers() []*Passenger {
	if m != nil {
		return m.Passengers
	}
	return nil
}

type Passenger struct {
	Gender               Passenger_Gender `protobuf:"varint,1,opt,name=gender,proto3,enum=g2rail.Passenger_Gender" json:"gender,omitempty"`
	Id                   string           `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string           `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	LastName             string           `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstName            string           `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Birthdate            string           `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string           `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Passport             string           `protobuf:"bytes,7,opt,name=passport,proto3" json:"passport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Passenger) Reset()         { *m = Passenger{} }
func (m *Passenger) String() string { return proto.CompactTextString(m) }
func (*Passenger) ProtoMessage()    {}
func (*Passenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{1}
}

func (m *Passenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passenger.Unmarshal(m, b)
}
func (m *Passenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passenger.Marshal(b, m, deterministic)
}
func (m *Passenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passenger.Merge(m, src)
}
func (m *Passenger) XXX_Size() int {
	return xxx_messageInfo_Passenger.Size(m)
}
func (m *Passenger) XXX_DiscardUnknown() {
	xxx_messageInfo_Passenger.DiscardUnknown(m)
}

var xxx_messageInfo_Passenger proto.InternalMessageInfo

func (m *Passenger) GetGender() Passenger_Gender {
	if m != nil {
		return m.Gender
	}
	return Passenger_male
}

func (m *Passenger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Passenger) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Passenger) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Passenger) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Passenger) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *Passenger) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Passenger) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

type OnlineOrderAsyncQueryRequest struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineOrderAsyncQueryRequest) Reset()         { *m = OnlineOrderAsyncQueryRequest{} }
func (m *OnlineOrderAsyncQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OnlineOrderAsyncQueryRequest) ProtoMessage()    {}
func (*OnlineOrderAsyncQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{2}
}

func (m *OnlineOrderAsyncQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Unmarshal(m, b)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Marshal(b, m, deterministic)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineOrderAsyncQueryRequest.Merge(m, src)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Size(m)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineOrderAsyncQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineOrderAsyncQueryRequest proto.InternalMessageInfo

func (m *OnlineOrderAsyncQueryRequest) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type OnlineOrderResponse struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loading              bool           `protobuf:"varint,14,opt,name=loading,proto3" json:"loading,omitempty"`
	OfflineFulfillment   bool           `protobuf:"varint,15,opt,name=offline_fulfillment,json=offlineFulfillment,proto3" json:"offline_fulfillment,omitempty"`
	TrainDescription     string         `protobuf:"bytes,16,opt,name=train_description,json=trainDescription,proto3" json:"train_description,omitempty"`
	Railway              *Railway       `protobuf:"bytes,2,opt,name=railway,proto3" json:"railway,omitempty"`
	From                 *Station       `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station       `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Departure            string         `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              string         `protobuf:"bytes,6,opt,name=arrival,proto3" json:"arrival,omitempty"`
	TicketPrice          *Price         `protobuf:"bytes,7,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	PaymentPrice         *Price         `protobuf:"bytes,8,opt,name=payment_price,json=paymentPrice,proto3" json:"payment_price,omitempty"`
	ChargingPrice        *Price         `protobuf:"bytes,9,opt,name=charging_price,json=chargingPrice,proto3" json:"charging_price,omitempty"`
	RebateAmount         *Price         `protobuf:"bytes,10,opt,name=rebate_amount,json=rebateAmount,proto3" json:"rebate_amount,omitempty"`
	Trains               []*Train       `protobuf:"bytes,17,rep,name=trains,proto3" json:"trains,omitempty"`
	Passengers           []*Passenger   `protobuf:"bytes,11,rep,name=passengers,proto3" json:"passengers,omitempty"`
	Tickets              []*Ticket      `protobuf:"bytes,12,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Records              []*PriceDetail `protobuf:"bytes,13,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OnlineOrderResponse) Reset()         { *m = OnlineOrderResponse{} }
func (m *OnlineOrderResponse) String() string { return proto.CompactTextString(m) }
func (*OnlineOrderResponse) ProtoMessage()    {}
func (*OnlineOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{3}
}

func (m *OnlineOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineOrderResponse.Unmarshal(m, b)
}
func (m *OnlineOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineOrderResponse.Marshal(b, m, deterministic)
}
func (m *OnlineOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineOrderResponse.Merge(m, src)
}
func (m *OnlineOrderResponse) XXX_Size() int {
	return xxx_messageInfo_OnlineOrderResponse.Size(m)
}
func (m *OnlineOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineOrderResponse proto.InternalMessageInfo

func (m *OnlineOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnlineOrderResponse) GetLoading() bool {
	if m != nil {
		return m.Loading
	}
	return false
}

func (m *OnlineOrderResponse) GetOfflineFulfillment() bool {
	if m != nil {
		return m.OfflineFulfillment
	}
	return false
}

func (m *OnlineOrderResponse) GetTrainDescription() string {
	if m != nil {
		return m.TrainDescription
	}
	return ""
}

func (m *OnlineOrderResponse) GetRailway() *Railway {
	if m != nil {
		return m.Railway
	}
	return nil
}

func (m *OnlineOrderResponse) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OnlineOrderResponse) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *OnlineOrderResponse) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *OnlineOrderResponse) GetArrival() string {
	if m != nil {
		return m.Arrival
	}
	return ""
}

func (m *OnlineOrderResponse) GetTicketPrice() *Price {
	if m != nil {
		return m.TicketPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetPaymentPrice() *Price {
	if m != nil {
		return m.PaymentPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetChargingPrice() *Price {
	if m != nil {
		return m.ChargingPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetRebateAmount() *Price {
	if m != nil {
		return m.RebateAmount
	}
	return nil
}

func (m *OnlineOrderResponse) GetTrains() []*Train {
	if m != nil {
		return m.Trains
	}
	return nil
}

func (m *OnlineOrderResponse) GetPassengers() []*Passenger {
	if m != nil {
		return m.Passengers
	}
	return nil
}

func (m *OnlineOrderResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *OnlineOrderResponse) GetRecords() []*PriceDetail {
	if m != nil {
		return m.Records
	}
	return nil
}

type Ticket struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 *Station `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Price                *Price   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{4}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Ticket) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Ticket) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type PriceDetail struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               *Price   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Target               string   `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceDetail) Reset()         { *m = PriceDetail{} }
func (m *PriceDetail) String() string { return proto.CompactTextString(m) }
func (*PriceDetail) ProtoMessage()    {}
func (*PriceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{5}
}

func (m *PriceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceDetail.Unmarshal(m, b)
}
func (m *PriceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceDetail.Marshal(b, m, deterministic)
}
func (m *PriceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceDetail.Merge(m, src)
}
func (m *PriceDetail) XXX_Size() int {
	return xxx_messageInfo_PriceDetail.Size(m)
}
func (m *PriceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PriceDetail proto.InternalMessageInfo

func (m *PriceDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PriceDetail) GetAmount() *Price {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *PriceDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PriceDetail) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PriceDetail) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterEnum("g2rail.Passenger_Gender", Passenger_Gender_name, Passenger_Gender_value)
	proto.RegisterType((*BookRequest)(nil), "g2rail.BookRequest")
	proto.RegisterType((*Passenger)(nil), "g2rail.Passenger")
	proto.RegisterType((*OnlineOrderAsyncQueryRequest)(nil), "g2rail.OnlineOrderAsyncQueryRequest")
	proto.RegisterType((*OnlineOrderResponse)(nil), "g2rail.OnlineOrderResponse")
	proto.RegisterType((*Ticket)(nil), "g2rail.Ticket")
	proto.RegisterType((*PriceDetail)(nil), "g2rail.PriceDetail")
}

func init() { proto.RegisterFile("lib/proto/OnlineOrders.proto", fileDescriptor_8d64e0e4515177ed) }

var fileDescriptor_8d64e0e4515177ed = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xe4, 0x44,
	0x10, 0xc5, 0x9e, 0x89, 0x67, 0x5c, 0xf3, 0x91, 0xa4, 0x03, 0xab, 0x56, 0x12, 0x20, 0x9a, 0xb0,
	0xd2, 0x20, 0xc4, 0x64, 0x19, 0xe0, 0xc4, 0x01, 0x25, 0xac, 0xd8, 0x03, 0x12, 0x1b, 0x1a, 0x4e,
	0x7b, 0x19, 0xf5, 0xd8, 0x35, 0x4e, 0x2b, 0xb6, 0xdb, 0x74, 0xf7, 0x2c, 0x9a, 0x23, 0xe2, 0x8a,
	0xc4, 0x6f, 0xe0, 0xca, 0x3f, 0xe1, 0x5f, 0xa1, 0x6e, 0xbb, 0x1d, 0x43, 0x06, 0xd8, 0x9b, 0xeb,
	0xbd, 0x57, 0x5d, 0xed, 0x7a, 0xe5, 0x32, 0x9c, 0xe7, 0x62, 0x7d, 0x55, 0x29, 0x69, 0xe4, 0xd5,
	0xcb, 0x32, 0x17, 0x25, 0xbe, 0x54, 0x29, 0x2a, 0xbd, 0x70, 0x10, 0x89, 0xb2, 0xa5, 0xe2, 0x22,
	0x3f, 0x7d, 0xf2, 0xa0, 0xfa, 0x4a, 0x16, 0x85, 0x2c, 0x6b, 0x7e, 0xf6, 0x73, 0x00, 0xa3, 0x1b,
	0x29, 0xef, 0x19, 0xfe, 0xb8, 0x45, 0x6d, 0xc8, 0x25, 0x4c, 0x34, 0x72, 0xb3, 0x52, 0xa8, 0x51,
	0xbd, 0xc6, 0x94, 0x06, 0x17, 0xc1, 0x7c, 0xc8, 0xc6, 0x16, 0x64, 0x0d, 0x46, 0x4e, 0x61, 0xa8,
	0x31, 0x31, 0x42, 0x96, 0x9a, 0x86, 0x17, 0xbd, 0x79, 0xcc, 0xda, 0x98, 0x7c, 0x02, 0x50, 0x71,
	0xad, 0xb1, 0xcc, 0x50, 0x69, 0xda, 0xbb, 0xe8, 0xcd, 0x47, 0xcb, 0xe3, 0x45, 0x7d, 0x8b, 0xc5,
	0xad, 0x67, 0x58, 0x47, 0x34, 0xfb, 0x2d, 0x84, 0xb8, 0x65, 0xc8, 0x33, 0x88, 0x32, 0x2c, 0x53,
	0x54, 0xae, 0xf4, 0x74, 0x49, 0x1f, 0x25, 0x2f, 0x5e, 0x38, 0x9e, 0x35, 0x3a, 0x32, 0x85, 0x50,
	0xa4, 0x74, 0x78, 0x11, 0xcc, 0x63, 0x16, 0x8a, 0x94, 0xbc, 0x0d, 0x07, 0xd5, 0x9d, 0x2c, 0x91,
	0x86, 0x0e, 0xaa, 0x03, 0x72, 0x06, 0x71, 0xce, 0xb5, 0x59, 0x95, 0xbc, 0x40, 0xda, 0x73, 0xcc,
	0xd0, 0x02, 0xdf, 0xf2, 0x02, 0xc9, 0xbb, 0x00, 0x1b, 0xa1, 0x3c, 0xdb, 0x77, 0x6c, 0xec, 0x10,
	0x47, 0x9f, 0x43, 0xbc, 0x16, 0xca, 0xdc, 0xa5, 0xdc, 0x20, 0x3d, 0xa8, 0xd9, 0x16, 0xb0, 0xf5,
	0xb0, 0xe0, 0x22, 0xa7, 0x51, 0x5d, 0xcf, 0x05, 0xb6, 0x49, 0xf6, 0x1d, 0x2b, 0xa9, 0x0c, 0x1d,
	0xd4, 0xe5, 0x7c, 0x3c, 0x7b, 0x0f, 0xa2, 0xfa, 0x1d, 0xc8, 0x10, 0xfa, 0x05, 0xcf, 0xf1, 0xe8,
	0x2d, 0x02, 0x10, 0x6d, 0xd0, 0x3d, 0x07, 0xb3, 0x2f, 0xe0, 0xbc, 0xe3, 0xe5, 0xb5, 0xde, 0x95,
	0xc9, 0x77, 0x5b, 0x54, 0x3b, 0xef, 0xd2, 0x19, 0xc4, 0xdc, 0x82, 0xab, 0x7b, 0xdc, 0xb9, 0x36,
	0xc5, 0x6c, 0xe8, 0x80, 0x6f, 0x70, 0x37, 0xfb, 0xf3, 0x00, 0x4e, 0x3a, 0xd9, 0x0c, 0x75, 0x25,
	0x4b, 0x8d, 0x4d, 0x9b, 0x82, 0xb6, 0x4d, 0x14, 0x06, 0xb9, 0xe4, 0xa9, 0x28, 0x33, 0x3a, 0x75,
	0x26, 0xfb, 0x90, 0x5c, 0xc1, 0x89, 0xdc, 0x6c, 0xec, 0x09, 0xab, 0xcd, 0x36, 0xdf, 0x88, 0x3c,
	0x2f, 0xb0, 0x34, 0xf4, 0xd0, 0xa9, 0x48, 0x43, 0x7d, 0xfd, 0xc0, 0x90, 0x8f, 0xe0, 0xd8, 0x28,
	0x2e, 0xca, 0x55, 0x8a, 0x3a, 0x51, 0xa2, 0xb2, 0xa3, 0x40, 0x8f, 0x5c, 0xa5, 0x23, 0x47, 0x3c,
	0x7f, 0xc0, 0xc9, 0x87, 0x30, 0xb0, 0x7e, 0xfe, 0xc4, 0x77, 0xce, 0xa0, 0xd1, 0xf2, 0xd0, 0x3b,
	0xcc, 0x6a, 0x98, 0x79, 0x9e, 0x5c, 0x42, 0x7f, 0xa3, 0x64, 0xe1, 0xec, 0xea, 0xe8, 0xbe, 0x37,
	0xdc, 0x9e, 0xc4, 0x1c, 0x49, 0xde, 0x87, 0xd0, 0x48, 0xe7, 0xd9, 0x1e, 0x49, 0x68, 0xa4, 0x75,
	0x2f, 0xc5, 0x8a, 0x2b, 0xb3, 0x55, 0xad, 0x7b, 0x2d, 0x60, 0xdb, 0xc0, 0x95, 0x12, 0xaf, 0xb9,
	0xf7, 0xcf, 0x87, 0xe4, 0x19, 0x8c, 0x8d, 0x48, 0xee, 0xd1, 0xac, 0x2a, 0x25, 0x12, 0x74, 0x2e,
	0x8e, 0x96, 0x93, 0x76, 0x1e, 0x2d, 0xc8, 0x46, 0xb5, 0xc4, 0x05, 0x64, 0x09, 0x93, 0x8a, 0xef,
	0x6c, 0x4b, 0x9a, 0x94, 0xe1, 0xbe, 0x94, 0x71, 0xa3, 0xa9, 0x73, 0x3e, 0x83, 0x69, 0x72, 0xc7,
	0x55, 0x26, 0xca, 0xac, 0x49, 0x8a, 0xf7, 0x25, 0x4d, 0xbc, 0xa8, 0xad, 0xa4, 0x70, 0xcd, 0x0d,
	0xae, 0x78, 0x21, 0xb7, 0xa5, 0xa1, 0xb0, 0xb7, 0x52, 0xad, 0xb9, 0x76, 0x12, 0xf2, 0x14, 0x22,
	0x67, 0x86, 0xa6, 0xc7, 0xee, 0xb3, 0x6c, 0xc5, 0x3f, 0x58, 0x94, 0x35, 0xe4, 0x3f, 0xbe, 0xe0,
	0xd1, 0x1b, 0x7c, 0xc1, 0x64, 0x0e, 0x83, 0xba, 0x0d, 0x9a, 0x8e, 0x9d, 0x7e, 0xda, 0x1e, 0xed,
	0x60, 0xe6, 0x69, 0xf2, 0x31, 0x0c, 0x14, 0x26, 0x52, 0xa5, 0x9a, 0x4e, 0x9c, 0xf2, 0xe4, 0x6f,
	0x37, 0x7e, 0x8e, 0x86, 0x8b, 0x9c, 0x79, 0xcd, 0xec, 0x97, 0x00, 0xa2, 0xfa, 0x88, 0x47, 0xe3,
	0xeb, 0x67, 0x23, 0xfc, 0xff, 0xd9, 0xe8, 0xfd, 0xfb, 0x6c, 0x5c, 0xc2, 0x41, 0xdd, 0xf4, 0xfe,
	0xbe, 0xfe, 0xd5, 0xdc, 0xec, 0xd7, 0x00, 0x46, 0x9d, 0xeb, 0x3d, 0xba, 0xca, 0x53, 0x88, 0x1a,
	0x17, 0xc2, 0x7d, 0xa7, 0x34, 0x24, 0x21, 0xd0, 0x37, 0xbb, 0xca, 0x2f, 0x1f, 0xf7, 0x6c, 0xb7,
	0x44, 0xc2, 0x0d, 0x66, 0x52, 0xed, 0x9a, 0xb5, 0xd3, 0xc6, 0xe4, 0x09, 0x44, 0x86, 0xab, 0x0c,
	0x4d, 0x33, 0xb4, 0x4d, 0xb4, 0xfc, 0x3d, 0x80, 0x71, 0x77, 0xd5, 0x93, 0xcf, 0xa1, 0x6f, 0x77,
	0x38, 0x69, 0x7b, 0xd9, 0xd9, 0xe8, 0xa7, 0xed, 0xfe, 0xbc, 0x6e, 0x16, 0x44, 0xbb, 0x10, 0x5e,
	0xc1, 0x3b, 0x6e, 0xab, 0x38, 0xa2, 0x73, 0x20, 0xf9, 0xc0, 0xa7, 0xfc, 0xd7, 0x12, 0x3a, 0x3d,
	0xdb, 0xa3, 0xf2, 0x67, 0xdf, 0x7c, 0x09, 0x53, 0x21, 0x17, 0x99, 0xaa, 0x92, 0x46, 0x75, 0x73,
	0xdc, 0xbd, 0xf2, 0xad, 0xfd, 0xf9, 0xdc, 0x06, 0xaf, 0x9a, 0xdf, 0xd3, 0x1f, 0xe1, 0xe1, 0x8b,
	0x25, 0xab, 0x3b, 0x26, 0x8d, 0x5c, 0x6f, 0x37, 0xeb, 0xc8, 0xfd, 0x9f, 0x3e, 0xfd, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0xc9, 0x0d, 0x3e, 0xdf, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlineOrdersClient is the client API for OnlineOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlineOrdersClient interface {
	// Send a search request
	Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineOrder(ctx context.Context, in *OnlineOrderAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineOrderResponse, error)
}

type onlineOrdersClient struct {
	cc *grpc.ClientConn
}

func NewOnlineOrdersClient(cc *grpc.ClientConn) OnlineOrdersClient {
	return &onlineOrdersClient{cc}
}

func (c *onlineOrdersClient) Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error) {
	out := new(AsyncKeyResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineOrders/Book", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineOrdersClient) QueryAsyncOnlineOrder(ctx context.Context, in *OnlineOrderAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineOrderResponse, error) {
	out := new(OnlineOrderResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineOrders/QueryAsyncOnlineOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineOrdersServer is the server API for OnlineOrders service.
type OnlineOrdersServer interface {
	// Send a search request
	Book(context.Context, *BookRequest) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineOrder(context.Context, *OnlineOrderAsyncQueryRequest) (*OnlineOrderResponse, error)
}

func RegisterOnlineOrdersServer(s *grpc.Server, srv OnlineOrdersServer) {
	s.RegisterService(&_OnlineOrders_serviceDesc, srv)
}

func _OnlineOrders_Book_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineOrdersServer).Book(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineOrders/Book",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineOrdersServer).Book(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineOrders_QueryAsyncOnlineOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineOrderAsyncQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineOrdersServer).QueryAsyncOnlineOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineOrders/QueryAsyncOnlineOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineOrdersServer).QueryAsyncOnlineOrder(ctx, req.(*OnlineOrderAsyncQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlineOrders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.OnlineOrders",
	HandlerType: (*OnlineOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Book",
			Handler:    _OnlineOrders_Book_Handler,
		},
		{
			MethodName: "QueryAsyncOnlineOrder",
			Handler:    _OnlineOrders_QueryAsyncOnlineOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/proto/OnlineOrders.proto",
}
