// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/OnlineTickets.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TicketFile_TicketType int32

const (
	TicketFile_pdf_ticket    TicketFile_TicketType = 0
	TicketFile_mobile_ticket TicketFile_TicketType = 1
)

var TicketFile_TicketType_name = map[int32]string{
	0: "pdf_ticket",
	1: "mobile_ticket",
}

var TicketFile_TicketType_value = map[string]int32{
	"pdf_ticket":    0,
	"mobile_ticket": 1,
}

func (x TicketFile_TicketType) String() string {
	return proto.EnumName(TicketFile_TicketType_name, int32(x))
}

func (TicketFile_TicketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cd5b9e53d9fc704, []int{2, 0}
}

type DownloadRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cd5b9e53d9fc704, []int{0}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type TicketsResponse struct {
	Files                []*TicketFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TicketsResponse) Reset()         { *m = TicketsResponse{} }
func (m *TicketsResponse) String() string { return proto.CompactTextString(m) }
func (*TicketsResponse) ProtoMessage()    {}
func (*TicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cd5b9e53d9fc704, []int{1}
}

func (m *TicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketsResponse.Unmarshal(m, b)
}
func (m *TicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketsResponse.Marshal(b, m, deterministic)
}
func (m *TicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketsResponse.Merge(m, src)
}
func (m *TicketsResponse) XXX_Size() int {
	return xxx_messageInfo_TicketsResponse.Size(m)
}
func (m *TicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TicketsResponse proto.InternalMessageInfo

func (m *TicketsResponse) GetFiles() []*TicketFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type TicketFile struct {
	File                 string                `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Type                 TicketFile_TicketType `protobuf:"varint,2,opt,name=type,proto3,enum=g2rail.TicketFile_TicketType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TicketFile) Reset()         { *m = TicketFile{} }
func (m *TicketFile) String() string { return proto.CompactTextString(m) }
func (*TicketFile) ProtoMessage()    {}
func (*TicketFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cd5b9e53d9fc704, []int{2}
}

func (m *TicketFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketFile.Unmarshal(m, b)
}
func (m *TicketFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketFile.Marshal(b, m, deterministic)
}
func (m *TicketFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketFile.Merge(m, src)
}
func (m *TicketFile) XXX_Size() int {
	return xxx_messageInfo_TicketFile.Size(m)
}
func (m *TicketFile) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketFile.DiscardUnknown(m)
}

var xxx_messageInfo_TicketFile proto.InternalMessageInfo

func (m *TicketFile) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *TicketFile) GetType() TicketFile_TicketType {
	if m != nil {
		return m.Type
	}
	return TicketFile_pdf_ticket
}

func init() {
	proto.RegisterEnum("g2rail.TicketFile_TicketType", TicketFile_TicketType_name, TicketFile_TicketType_value)
	proto.RegisterType((*DownloadRequest)(nil), "g2rail.DownloadRequest")
	proto.RegisterType((*TicketsResponse)(nil), "g2rail.TicketsResponse")
	proto.RegisterType((*TicketFile)(nil), "g2rail.TicketFile")
}

func init() { proto.RegisterFile("lib/proto/OnlineTickets.proto", fileDescriptor_8cd5b9e53d9fc704) }

var fileDescriptor_8cd5b9e53d9fc704 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0x9c, 0x73, 0x3e, 0xd9, 0xaa, 0xef, 0xb2, 0x2a, 0x0c, 0x4a, 0x4f, 0x3d, 0x48,
	0x8b, 0xf5, 0xa8, 0x07, 0x19, 0xa2, 0x78, 0x10, 0x47, 0xd8, 0xc9, 0xcb, 0x58, 0xd7, 0xd7, 0x11,
	0x8c, 0x4d, 0x6c, 0x3b, 0x64, 0x77, 0x3f, 0x8d, 0x9f, 0x52, 0x9a, 0xa6, 0x4a, 0xf5, 0xf6, 0xfa,
	0xeb, 0x9f, 0xdf, 0x4b, 0xfe, 0x81, 0xa9, 0x14, 0x49, 0xa4, 0x0b, 0x55, 0xa9, 0xe8, 0x39, 0x97,
	0x22, 0xa7, 0x85, 0x58, 0xbf, 0x52, 0x55, 0x86, 0x86, 0xe1, 0x60, 0x13, 0x17, 0x2b, 0x21, 0xfd,
	0x0b, 0x70, 0xee, 0xd4, 0x47, 0x2e, 0xd5, 0x2a, 0xe5, 0xf4, 0xbe, 0xa5, 0xb2, 0xc2, 0x33, 0x18,
	0xaa, 0x22, 0xa5, 0x62, 0x29, 0x52, 0x97, 0x79, 0x2c, 0x38, 0xe2, 0x87, 0xe6, 0xfb, 0x31, 0xf5,
	0xaf, 0xc1, 0xb1, 0x1a, 0x4e, 0xa5, 0x56, 0x79, 0x49, 0x18, 0xc0, 0x41, 0x26, 0x24, 0x95, 0x2e,
	0xf3, 0xf6, 0x83, 0xe3, 0x18, 0xc3, 0x46, 0x1c, 0x36, 0xb9, 0x7b, 0x21, 0x89, 0x37, 0x01, 0xff,
	0x93, 0x01, 0xfc, 0x52, 0x44, 0xe8, 0xd7, 0xdc, 0xae, 0x30, 0x33, 0x5e, 0x42, 0xbf, 0xda, 0x69,
	0x72, 0x7b, 0x1e, 0x0b, 0xc6, 0xf1, 0xf4, 0xbf, 0xcb, 0x8e, 0x8b, 0x9d, 0x26, 0x6e, 0xa2, 0x7e,
	0xd4, 0x4a, 0x6b, 0x86, 0x63, 0x00, 0x9d, 0x66, 0xcb, 0xca, 0x90, 0x93, 0x3d, 0x3c, 0x85, 0xd1,
	0x9b, 0x4a, 0x84, 0xa4, 0x16, 0xb1, 0xf8, 0x09, 0x46, 0x9d, 0x42, 0xf0, 0x06, 0x86, 0x6d, 0x05,
	0x38, 0x69, 0x57, 0xfe, 0x29, 0xe5, 0x7c, 0xd2, 0x3d, 0xcb, 0xcf, 0xfd, 0x67, 0xb7, 0x30, 0x16,
	0x2a, 0xdc, 0x14, 0x7a, 0x6d, 0x13, 0x33, 0xec, 0xe8, 0xe7, 0x75, 0xdd, 0x73, 0xf6, 0x62, 0x0b,
	0xff, 0xea, 0x39, 0x0f, 0x31, 0xaf, 0x45, 0xe6, 0x47, 0xb2, 0xcd, 0x92, 0x81, 0x79, 0x91, 0xab,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x53, 0xb6, 0x46, 0xb2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlineTicketsClient is the client API for OnlineTickets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlineTicketsClient interface {
	// Send a tickets downloading request
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*TicketsResponse, error)
}

type onlineTicketsClient struct {
	cc *grpc.ClientConn
}

func NewOnlineTicketsClient(cc *grpc.ClientConn) OnlineTicketsClient {
	return &onlineTicketsClient{cc}
}

func (c *onlineTicketsClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*TicketsResponse, error) {
	out := new(TicketsResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineTickets/Download", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineTicketsServer is the server API for OnlineTickets service.
type OnlineTicketsServer interface {
	// Send a tickets downloading request
	Download(context.Context, *DownloadRequest) (*TicketsResponse, error)
}

func RegisterOnlineTicketsServer(s *grpc.Server, srv OnlineTicketsServer) {
	s.RegisterService(&_OnlineTickets_serviceDesc, srv)
}

func _OnlineTickets_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineTicketsServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineTickets/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineTicketsServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlineTickets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.OnlineTickets",
	HandlerType: (*OnlineTicketsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _OnlineTickets_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/proto/OnlineTickets.proto",
}
