// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/OnlineOrders.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookRequest struct {
	SeatReserved         bool         `protobuf:"varint,1,opt,name=seat_reserved,json=seatReserved,proto3" json:"seat_reserved,omitempty"`
	Sections             []string     `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Passengers           []*Passenger `protobuf:"bytes,3,rep,name=passengers,proto3" json:"passengers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{0}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetSeatReserved() bool {
	if m != nil {
		return m.SeatReserved
	}
	return false
}

func (m *BookRequest) GetSections() []string {
	if m != nil {
		return m.Sections
	}
	return nil
}

func (m *BookRequest) GetPassengers() []*Passenger {
	if m != nil {
		return m.Passengers
	}
	return nil
}

type OnlineOrderAsyncQueryRequest struct {
	AsyncKey             string   `protobuf:"bytes,1,opt,name=async_key,json=asyncKey,proto3" json:"async_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineOrderAsyncQueryRequest) Reset()         { *m = OnlineOrderAsyncQueryRequest{} }
func (m *OnlineOrderAsyncQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OnlineOrderAsyncQueryRequest) ProtoMessage()    {}
func (*OnlineOrderAsyncQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{1}
}

func (m *OnlineOrderAsyncQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Unmarshal(m, b)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Marshal(b, m, deterministic)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineOrderAsyncQueryRequest.Merge(m, src)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OnlineOrderAsyncQueryRequest.Size(m)
}
func (m *OnlineOrderAsyncQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineOrderAsyncQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineOrderAsyncQueryRequest proto.InternalMessageInfo

func (m *OnlineOrderAsyncQueryRequest) GetAsyncKey() string {
	if m != nil {
		return m.AsyncKey
	}
	return ""
}

type OnlineOrderResponse struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loading              bool           `protobuf:"varint,14,opt,name=loading,proto3" json:"loading,omitempty"`
	OfflineFulfillment   bool           `protobuf:"varint,15,opt,name=offline_fulfillment,json=offlineFulfillment,proto3" json:"offline_fulfillment,omitempty"`
	TrainDescription     string         `protobuf:"bytes,16,opt,name=train_description,json=trainDescription,proto3" json:"train_description,omitempty"`
	Railway              *Railway       `protobuf:"bytes,2,opt,name=railway,proto3" json:"railway,omitempty"`
	From                 *Station       `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Station       `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Departure            string         `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival              string         `protobuf:"bytes,6,opt,name=arrival,proto3" json:"arrival,omitempty"`
	TicketPrice          *Price         `protobuf:"bytes,7,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	PaymentPrice         *Price         `protobuf:"bytes,8,opt,name=payment_price,json=paymentPrice,proto3" json:"payment_price,omitempty"`
	ChargingPrice        *Price         `protobuf:"bytes,9,opt,name=charging_price,json=chargingPrice,proto3" json:"charging_price,omitempty"`
	RebateAmount         *Price         `protobuf:"bytes,10,opt,name=rebate_amount,json=rebateAmount,proto3" json:"rebate_amount,omitempty"`
	Trains               []*Train       `protobuf:"bytes,17,rep,name=trains,proto3" json:"trains,omitempty"`
	Passengers           []*Passenger   `protobuf:"bytes,11,rep,name=passengers,proto3" json:"passengers,omitempty"`
	Tickets              []*Ticket      `protobuf:"bytes,12,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Records              []*PriceDetail `protobuf:"bytes,13,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OnlineOrderResponse) Reset()         { *m = OnlineOrderResponse{} }
func (m *OnlineOrderResponse) String() string { return proto.CompactTextString(m) }
func (*OnlineOrderResponse) ProtoMessage()    {}
func (*OnlineOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d64e0e4515177ed, []int{2}
}

func (m *OnlineOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineOrderResponse.Unmarshal(m, b)
}
func (m *OnlineOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineOrderResponse.Marshal(b, m, deterministic)
}
func (m *OnlineOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineOrderResponse.Merge(m, src)
}
func (m *OnlineOrderResponse) XXX_Size() int {
	return xxx_messageInfo_OnlineOrderResponse.Size(m)
}
func (m *OnlineOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineOrderResponse proto.InternalMessageInfo

func (m *OnlineOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnlineOrderResponse) GetLoading() bool {
	if m != nil {
		return m.Loading
	}
	return false
}

func (m *OnlineOrderResponse) GetOfflineFulfillment() bool {
	if m != nil {
		return m.OfflineFulfillment
	}
	return false
}

func (m *OnlineOrderResponse) GetTrainDescription() string {
	if m != nil {
		return m.TrainDescription
	}
	return ""
}

func (m *OnlineOrderResponse) GetRailway() *Railway {
	if m != nil {
		return m.Railway
	}
	return nil
}

func (m *OnlineOrderResponse) GetFrom() *Station {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OnlineOrderResponse) GetTo() *Station {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *OnlineOrderResponse) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *OnlineOrderResponse) GetArrival() string {
	if m != nil {
		return m.Arrival
	}
	return ""
}

func (m *OnlineOrderResponse) GetTicketPrice() *Price {
	if m != nil {
		return m.TicketPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetPaymentPrice() *Price {
	if m != nil {
		return m.PaymentPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetChargingPrice() *Price {
	if m != nil {
		return m.ChargingPrice
	}
	return nil
}

func (m *OnlineOrderResponse) GetRebateAmount() *Price {
	if m != nil {
		return m.RebateAmount
	}
	return nil
}

func (m *OnlineOrderResponse) GetTrains() []*Train {
	if m != nil {
		return m.Trains
	}
	return nil
}

func (m *OnlineOrderResponse) GetPassengers() []*Passenger {
	if m != nil {
		return m.Passengers
	}
	return nil
}

func (m *OnlineOrderResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *OnlineOrderResponse) GetRecords() []*PriceDetail {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*BookRequest)(nil), "g2rail.BookRequest")
	proto.RegisterType((*OnlineOrderAsyncQueryRequest)(nil), "g2rail.OnlineOrderAsyncQueryRequest")
	proto.RegisterType((*OnlineOrderResponse)(nil), "g2rail.OnlineOrderResponse")
}

func init() { proto.RegisterFile("lib/proto/OnlineOrders.proto", fileDescriptor_8d64e0e4515177ed) }

var fileDescriptor_8d64e0e4515177ed = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0xc7, 0x95, 0x4d, 0x9b, 0x97, 0xc9, 0x4b, 0x1b, 0x57, 0xcf, 0x23, 0x2b, 0xad, 0x44, 0xd4,
	0x82, 0x14, 0x84, 0x48, 0x21, 0xc0, 0x89, 0x03, 0x6a, 0xa9, 0xe0, 0xc0, 0xa1, 0xc5, 0x70, 0xea,
	0x25, 0x72, 0x76, 0x27, 0xc1, 0xca, 0x66, 0xbd, 0xd8, 0x4e, 0xd1, 0x1e, 0xf9, 0x28, 0x5c, 0xf9,
	0x26, 0x7c, 0x2b, 0x64, 0xef, 0x7a, 0xb3, 0x45, 0x11, 0xe2, 0xe8, 0xff, 0xff, 0x37, 0xe3, 0xb1,
	0x3d, 0x63, 0x38, 0x89, 0xc5, 0xfc, 0x3c, 0x55, 0xd2, 0xc8, 0xf3, 0xeb, 0x24, 0x16, 0x09, 0x5e,
	0xab, 0x08, 0x95, 0x9e, 0x38, 0x89, 0x34, 0x96, 0x53, 0xc5, 0x45, 0x3c, 0xfc, 0x7f, 0x4b, 0xbd,
	0x95, 0xeb, 0xb5, 0x4c, 0x72, 0xff, 0xf4, 0x7b, 0x0d, 0x3a, 0x97, 0x52, 0xae, 0x18, 0x7e, 0xdd,
	0xa0, 0x36, 0xe4, 0x0c, 0x7a, 0x1a, 0xb9, 0x99, 0x29, 0xd4, 0xa8, 0xee, 0x30, 0xa2, 0xb5, 0x51,
	0x6d, 0xdc, 0x62, 0x5d, 0x2b, 0xb2, 0x42, 0x23, 0x43, 0x68, 0x69, 0x0c, 0x8d, 0x90, 0x89, 0xa6,
	0xc1, 0xa8, 0x3e, 0x6e, 0xb3, 0x72, 0x4d, 0x9e, 0x03, 0xa4, 0x5c, 0x6b, 0x4c, 0x96, 0xa8, 0x34,
	0xad, 0x8f, 0xea, 0xe3, 0xce, 0x74, 0x30, 0xc9, 0xab, 0x98, 0xdc, 0x78, 0x87, 0x55, 0xa0, 0xd3,
	0xd7, 0x70, 0x52, 0xa9, 0xfc, 0x42, 0x67, 0x49, 0xf8, 0x71, 0x83, 0x2a, 0xf3, 0x35, 0x1d, 0x43,
	0x9b, 0x5b, 0x71, 0xb6, 0xc2, 0xcc, 0xd5, 0xd3, 0x66, 0x2d, 0x27, 0x7c, 0xc0, 0xec, 0xf4, 0xd7,
	0x3e, 0x1c, 0x55, 0xa2, 0x19, 0xea, 0x54, 0x26, 0x1a, 0x49, 0x1f, 0x02, 0x11, 0x15, 0x74, 0x20,
	0x22, 0x42, 0xa1, 0x19, 0x4b, 0x1e, 0x89, 0x64, 0x49, 0xfb, 0xee, 0x48, 0x7e, 0x49, 0xce, 0xe1,
	0x48, 0x2e, 0x16, 0x36, 0xc3, 0x6c, 0xb1, 0x89, 0x17, 0x22, 0x8e, 0xd7, 0x98, 0x18, 0x7a, 0xe0,
	0x28, 0x52, 0x58, 0xef, 0xb6, 0x0e, 0x79, 0x02, 0x03, 0xa3, 0xb8, 0x48, 0x66, 0x11, 0xea, 0x50,
	0x89, 0xd4, 0x1e, 0x9c, 0x1e, 0xba, 0x9d, 0x0e, 0x9d, 0x71, 0xb5, 0xd5, 0xc9, 0x63, 0x68, 0xda,
	0xa3, 0x7f, 0xe3, 0x19, 0x0d, 0x46, 0xb5, 0x71, 0x67, 0x7a, 0xe0, 0x2f, 0x83, 0xe5, 0x32, 0xf3,
	0x3e, 0x39, 0x83, 0xbd, 0x85, 0x92, 0x6b, 0x5a, 0xbf, 0xcf, 0x7d, 0x32, 0xdc, 0x66, 0x62, 0xce,
	0x24, 0x0f, 0x20, 0x30, 0x92, 0xee, 0xed, 0x46, 0x02, 0x23, 0xc9, 0x09, 0xb4, 0x23, 0x4c, 0xb9,
	0x32, 0x1b, 0x85, 0x74, 0xdf, 0x55, 0xb5, 0x15, 0xec, 0x35, 0x70, 0xa5, 0xc4, 0x1d, 0x8f, 0x69,
	0xc3, 0x79, 0x7e, 0x49, 0x9e, 0x41, 0xd7, 0x88, 0x70, 0x85, 0x66, 0x96, 0x2a, 0x11, 0x22, 0x6d,
	0xba, 0x2d, 0x7a, 0xe5, 0xd3, 0x59, 0x91, 0x75, 0x72, 0xc4, 0x2d, 0xc8, 0x14, 0x7a, 0x29, 0xcf,
	0xec, 0x95, 0x14, 0x21, 0xad, 0x5d, 0x21, 0xdd, 0x82, 0xc9, 0x63, 0x5e, 0x42, 0x3f, 0xfc, 0xc2,
	0xd5, 0x52, 0x24, 0xcb, 0x22, 0xa8, 0xbd, 0x2b, 0xa8, 0xe7, 0xa1, 0x72, 0x27, 0x85, 0x73, 0x6e,
	0x70, 0xc6, 0xd7, 0x72, 0x93, 0x18, 0x0a, 0x3b, 0x77, 0xca, 0x99, 0x0b, 0x87, 0x90, 0x47, 0xd0,
	0x70, 0x8f, 0xa1, 0xe9, 0xc0, 0x35, 0x61, 0x09, 0x7f, 0xb6, 0x2a, 0x2b, 0xcc, 0x3f, 0xfa, 0xb5,
	0xf3, 0x0f, 0xfd, 0x4a, 0xc6, 0xd0, 0xcc, 0xaf, 0x41, 0xd3, 0xae, 0xe3, 0xfb, 0x65, 0x6a, 0x27,
	0x33, 0x6f, 0x93, 0xa7, 0xd0, 0x54, 0x18, 0x4a, 0x15, 0x69, 0xda, 0x73, 0xe4, 0xd1, 0xbd, 0x8a,
	0xaf, 0xd0, 0x70, 0x11, 0x33, 0xcf, 0x4c, 0x7f, 0xd4, 0xa0, 0x5b, 0x9d, 0x61, 0xf2, 0x0a, 0xf6,
	0xec, 0x70, 0x92, 0x32, 0xac, 0x32, 0xaa, 0x43, 0xea, 0xc5, 0x8b, 0x62, 0x16, 0xca, 0xde, 0xbf,
	0x85, 0xff, 0xdc, 0x00, 0x39, 0xa3, 0x92, 0x90, 0x3c, 0xf4, 0x21, 0x7f, 0x9b, 0xb7, 0xe1, 0xf1,
	0x0e, 0xca, 0xe7, 0xbe, 0x7c, 0x03, 0x7d, 0x21, 0x27, 0x4b, 0x95, 0x86, 0x05, 0x75, 0x39, 0xa8,
	0x96, 0x7c, 0x63, 0x7f, 0x95, 0x9b, 0xda, 0x6d, 0xf1, 0xef, 0xfc, 0x0c, 0x0e, 0xde, 0x4f, 0x59,
	0x7e, 0x60, 0x69, 0xe4, 0x7c, 0xb3, 0x98, 0x37, 0xdc, 0xc7, 0xf3, 0xe2, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0x87, 0xe2, 0xdf, 0xb8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlineOrdersClient is the client API for OnlineOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlineOrdersClient interface {
	// Send a book request
	Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineOrder(ctx context.Context, in *OnlineOrderAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineOrderResponse, error)
}

type onlineOrdersClient struct {
	cc *grpc.ClientConn
}

func NewOnlineOrdersClient(cc *grpc.ClientConn) OnlineOrdersClient {
	return &onlineOrdersClient{cc}
}

func (c *onlineOrdersClient) Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*AsyncKeyResponse, error) {
	out := new(AsyncKeyResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineOrders/Book", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineOrdersClient) QueryAsyncOnlineOrder(ctx context.Context, in *OnlineOrderAsyncQueryRequest, opts ...grpc.CallOption) (*OnlineOrderResponse, error) {
	out := new(OnlineOrderResponse)
	err := c.cc.Invoke(ctx, "/g2rail.OnlineOrders/QueryAsyncOnlineOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineOrdersServer is the server API for OnlineOrders service.
type OnlineOrdersServer interface {
	// Send a book request
	Book(context.Context, *BookRequest) (*AsyncKeyResponse, error)
	// Service to query async result by using the async key
	QueryAsyncOnlineOrder(context.Context, *OnlineOrderAsyncQueryRequest) (*OnlineOrderResponse, error)
}

func RegisterOnlineOrdersServer(s *grpc.Server, srv OnlineOrdersServer) {
	s.RegisterService(&_OnlineOrders_serviceDesc, srv)
}

func _OnlineOrders_Book_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineOrdersServer).Book(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineOrders/Book",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineOrdersServer).Book(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineOrders_QueryAsyncOnlineOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineOrderAsyncQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineOrdersServer).QueryAsyncOnlineOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.OnlineOrders/QueryAsyncOnlineOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineOrdersServer).QueryAsyncOnlineOrder(ctx, req.(*OnlineOrderAsyncQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlineOrders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.OnlineOrders",
	HandlerType: (*OnlineOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Book",
			Handler:    _OnlineOrders_Book_Handler,
		},
		{
			MethodName: "QueryAsyncOnlineOrder",
			Handler:    _OnlineOrders_QueryAsyncOnlineOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/proto/OnlineOrders.proto",
}
