// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/Suggestions.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SuggestionRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Departure            string   `protobuf:"bytes,2,opt,name=departure,proto3" json:"departure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestionRequest) Reset()         { *m = SuggestionRequest{} }
func (m *SuggestionRequest) String() string { return proto.CompactTextString(m) }
func (*SuggestionRequest) ProtoMessage()    {}
func (*SuggestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f864af88ae52c64, []int{0}
}

func (m *SuggestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestionRequest.Unmarshal(m, b)
}
func (m *SuggestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestionRequest.Marshal(b, m, deterministic)
}
func (m *SuggestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestionRequest.Merge(m, src)
}
func (m *SuggestionRequest) XXX_Size() int {
	return xxx_messageInfo_SuggestionRequest.Size(m)
}
func (m *SuggestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestionRequest proto.InternalMessageInfo

func (m *SuggestionRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SuggestionRequest) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

type SuggestionsResponse struct {
	Suggestions          []*Suggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SuggestionsResponse) Reset()         { *m = SuggestionsResponse{} }
func (m *SuggestionsResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestionsResponse) ProtoMessage()    {}
func (*SuggestionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f864af88ae52c64, []int{1}
}

func (m *SuggestionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestionsResponse.Unmarshal(m, b)
}
func (m *SuggestionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestionsResponse.Marshal(b, m, deterministic)
}
func (m *SuggestionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestionsResponse.Merge(m, src)
}
func (m *SuggestionsResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestionsResponse.Size(m)
}
func (m *SuggestionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestionsResponse proto.InternalMessageInfo

func (m *SuggestionsResponse) GetSuggestions() []*Suggestion {
	if m != nil {
		return m.Suggestions
	}
	return nil
}

type Suggestion struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ToCode               string   `protobuf:"bytes,3,opt,name=to_code,json=toCode,proto3" json:"to_code,omitempty"`
	ToValue              string   `protobuf:"bytes,4,opt,name=to_value,json=toValue,proto3" json:"to_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suggestion) Reset()         { *m = Suggestion{} }
func (m *Suggestion) String() string { return proto.CompactTextString(m) }
func (*Suggestion) ProtoMessage()    {}
func (*Suggestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f864af88ae52c64, []int{2}
}

func (m *Suggestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suggestion.Unmarshal(m, b)
}
func (m *Suggestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suggestion.Marshal(b, m, deterministic)
}
func (m *Suggestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suggestion.Merge(m, src)
}
func (m *Suggestion) XXX_Size() int {
	return xxx_messageInfo_Suggestion.Size(m)
}
func (m *Suggestion) XXX_DiscardUnknown() {
	xxx_messageInfo_Suggestion.DiscardUnknown(m)
}

var xxx_messageInfo_Suggestion proto.InternalMessageInfo

func (m *Suggestion) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Suggestion) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Suggestion) GetToCode() string {
	if m != nil {
		return m.ToCode
	}
	return ""
}

func (m *Suggestion) GetToValue() string {
	if m != nil {
		return m.ToValue
	}
	return ""
}

func init() {
	proto.RegisterType((*SuggestionRequest)(nil), "g2rail.SuggestionRequest")
	proto.RegisterType((*SuggestionsResponse)(nil), "g2rail.SuggestionsResponse")
	proto.RegisterType((*Suggestion)(nil), "g2rail.Suggestion")
}

func init() { proto.RegisterFile("lib/proto/Suggestions.proto", fileDescriptor_5f864af88ae52c64) }

var fileDescriptor_5f864af88ae52c64 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x1f, 0xa9, 0x9d, 0x80, 0x8f, 0x55, 0x30, 0xb5, 0x1e, 0x4a, 0x4e, 0x3d, 0xa5,
	0x10, 0x3d, 0x2b, 0xd4, 0x43, 0x0f, 0x82, 0xd4, 0x08, 0x1e, 0xbc, 0x94, 0xa4, 0x5d, 0x43, 0x24,
	0x74, 0x92, 0x7d, 0x08, 0xfe, 0x4b, 0xfe, 0x95, 0xb2, 0xb3, 0xd1, 0x2c, 0xd8, 0xdb, 0xce, 0xf7,
	0xfb, 0x76, 0xe7, 0x9b, 0x59, 0x98, 0x56, 0x65, 0xbe, 0xa8, 0x05, 0x2a, 0x5c, 0xbc, 0xe8, 0xa2,
	0xe0, 0x52, 0x95, 0xb8, 0x97, 0x31, 0x29, 0xcc, 0x2f, 0x12, 0x91, 0x95, 0x55, 0xb4, 0x82, 0xb3,
	0x0e, 0xa6, 0xbc, 0xd1, 0x5c, 0x2a, 0x76, 0x01, 0xc3, 0x46, 0x73, 0xf1, 0x15, 0x7a, 0x33, 0x6f,
	0x3e, 0x4e, 0x6d, 0xc1, 0xae, 0x61, 0xbc, 0xe3, 0x75, 0x26, 0x94, 0x16, 0x3c, 0xec, 0x11, 0xe9,
	0x84, 0xe8, 0x11, 0xce, 0x9d, 0x2e, 0x29, 0x97, 0x35, 0xee, 0x25, 0x67, 0xb7, 0x10, 0xc8, 0x4e,
	0x0e, 0xbd, 0x59, 0x7f, 0x1e, 0x24, 0x2c, 0xb6, 0xdd, 0x63, 0xa7, 0xb5, 0x6b, 0x8b, 0x3e, 0x00,
	0x3a, 0xc4, 0x18, 0x0c, 0xb6, 0xb8, 0xe3, 0x6d, 0x1a, 0x3a, 0x9b, 0x88, 0x9f, 0x59, 0xa5, 0x7f,
	0x83, 0xd8, 0x82, 0x5d, 0xc2, 0x48, 0xe1, 0x86, 0xcc, 0x7d, 0xd2, 0x7d, 0x85, 0x0f, 0xc6, 0x3e,
	0x81, 0x23, 0x85, 0x1b, 0x7b, 0x63, 0x40, 0x64, 0xa4, 0xf0, 0xd5, 0x94, 0xc9, 0x13, 0x04, 0x4e,
	0x70, 0x76, 0x0f, 0xc3, 0x67, 0x1a, 0x77, 0x72, 0x20, 0xa4, 0xdd, 0xcf, 0xd5, 0xf4, 0x3f, 0xfa,
	0x9b, 0x78, 0x79, 0x07, 0xc7, 0x25, 0xc6, 0x85, 0xa8, 0xb7, 0xad, 0x6b, 0x79, 0xea, 0xd8, 0xd6,
	0x66, 0xfb, 0x6b, 0xef, 0xad, 0xdd, 0xff, 0x77, 0xef, 0x64, 0x95, 0xa4, 0xe6, 0x29, 0x02, 0xb9,
	0x7e, 0xcf, 0x7d, 0xfa, 0xa0, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x1c, 0x7d, 0x50,
	0xbf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SuggestionsClient is the client API for Suggestions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuggestionsClient interface {
	// Send a station query request
	Query(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error)
}

type suggestionsClient struct {
	cc *grpc.ClientConn
}

func NewSuggestionsClient(cc *grpc.ClientConn) SuggestionsClient {
	return &suggestionsClient{cc}
}

func (c *suggestionsClient) Query(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionsResponse, error) {
	out := new(SuggestionsResponse)
	err := c.cc.Invoke(ctx, "/g2rail.Suggestions/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestionsServer is the server API for Suggestions service.
type SuggestionsServer interface {
	// Send a station query request
	Query(context.Context, *SuggestionRequest) (*SuggestionsResponse, error)
}

func RegisterSuggestionsServer(s *grpc.Server, srv SuggestionsServer) {
	s.RegisterService(&_Suggestions_serviceDesc, srv)
}

func _Suggestions_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestionsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.Suggestions/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestionsServer).Query(ctx, req.(*SuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Suggestions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.Suggestions",
	HandlerType: (*SuggestionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Suggestions_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/proto/Suggestions.proto",
}
