// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/TrainSchedules.proto

package g2rail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DepartureBoardRequest struct {
	StationCode          string   `protobuf:"bytes,1,opt,name=station_code,json=stationCode,proto3" json:"station_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartureBoardRequest) Reset()         { *m = DepartureBoardRequest{} }
func (m *DepartureBoardRequest) String() string { return proto.CompactTextString(m) }
func (*DepartureBoardRequest) ProtoMessage()    {}
func (*DepartureBoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{0}
}

func (m *DepartureBoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartureBoardRequest.Unmarshal(m, b)
}
func (m *DepartureBoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartureBoardRequest.Marshal(b, m, deterministic)
}
func (m *DepartureBoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartureBoardRequest.Merge(m, src)
}
func (m *DepartureBoardRequest) XXX_Size() int {
	return xxx_messageInfo_DepartureBoardRequest.Size(m)
}
func (m *DepartureBoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartureBoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepartureBoardRequest proto.InternalMessageInfo

func (m *DepartureBoardRequest) GetStationCode() string {
	if m != nil {
		return m.StationCode
	}
	return ""
}

type DepartureBoardResponse struct {
	Departures           []*Departure `protobuf:"bytes,1,rep,name=departures,proto3" json:"departures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DepartureBoardResponse) Reset()         { *m = DepartureBoardResponse{} }
func (m *DepartureBoardResponse) String() string { return proto.CompactTextString(m) }
func (*DepartureBoardResponse) ProtoMessage()    {}
func (*DepartureBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{1}
}

func (m *DepartureBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartureBoardResponse.Unmarshal(m, b)
}
func (m *DepartureBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartureBoardResponse.Marshal(b, m, deterministic)
}
func (m *DepartureBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartureBoardResponse.Merge(m, src)
}
func (m *DepartureBoardResponse) XXX_Size() int {
	return xxx_messageInfo_DepartureBoardResponse.Size(m)
}
func (m *DepartureBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartureBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepartureBoardResponse proto.InternalMessageInfo

func (m *DepartureBoardResponse) GetDepartures() []*Departure {
	if m != nil {
		return m.Departures
	}
	return nil
}

type Departure struct {
	DepartureCode        string   `protobuf:"bytes,1,opt,name=departure_code,json=departureCode,proto3" json:"departure_code,omitempty"`
	DepartureName        string   `protobuf:"bytes,2,opt,name=departure_name,json=departureName,proto3" json:"departure_name,omitempty"`
	DestinationCode      string   `protobuf:"bytes,3,opt,name=destination_code,json=destinationCode,proto3" json:"destination_code,omitempty"`
	DestinationName      string   `protobuf:"bytes,4,opt,name=destination_name,json=destinationName,proto3" json:"destination_name,omitempty"`
	PlannedDepHourMin    string   `protobuf:"bytes,5,opt,name=planned_dep_hour_min,json=plannedDepHourMin,proto3" json:"planned_dep_hour_min,omitempty"`
	ActualDepHourMin     string   `protobuf:"bytes,6,opt,name=actual_dep_hour_min,json=actualDepHourMin,proto3" json:"actual_dep_hour_min,omitempty"`
	PlannedArrHourMin    string   `protobuf:"bytes,7,opt,name=planned_arr_hour_min,json=plannedArrHourMin,proto3" json:"planned_arr_hour_min,omitempty"`
	ActualArrHourMin     string   `protobuf:"bytes,8,opt,name=actual_arr_hour_min,json=actualArrHourMin,proto3" json:"actual_arr_hour_min,omitempty"`
	TrainNumber          string   `protobuf:"bytes,9,opt,name=train_number,json=trainNumber,proto3" json:"train_number,omitempty"`
	Via                  string   `protobuf:"bytes,10,opt,name=via,proto3" json:"via,omitempty"`
	Platform             string   `protobuf:"bytes,11,opt,name=platform,proto3" json:"platform,omitempty"`
	Message              string   `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Departure) Reset()         { *m = Departure{} }
func (m *Departure) String() string { return proto.CompactTextString(m) }
func (*Departure) ProtoMessage()    {}
func (*Departure) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{2}
}

func (m *Departure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Departure.Unmarshal(m, b)
}
func (m *Departure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Departure.Marshal(b, m, deterministic)
}
func (m *Departure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Departure.Merge(m, src)
}
func (m *Departure) XXX_Size() int {
	return xxx_messageInfo_Departure.Size(m)
}
func (m *Departure) XXX_DiscardUnknown() {
	xxx_messageInfo_Departure.DiscardUnknown(m)
}

var xxx_messageInfo_Departure proto.InternalMessageInfo

func (m *Departure) GetDepartureCode() string {
	if m != nil {
		return m.DepartureCode
	}
	return ""
}

func (m *Departure) GetDepartureName() string {
	if m != nil {
		return m.DepartureName
	}
	return ""
}

func (m *Departure) GetDestinationCode() string {
	if m != nil {
		return m.DestinationCode
	}
	return ""
}

func (m *Departure) GetDestinationName() string {
	if m != nil {
		return m.DestinationName
	}
	return ""
}

func (m *Departure) GetPlannedDepHourMin() string {
	if m != nil {
		return m.PlannedDepHourMin
	}
	return ""
}

func (m *Departure) GetActualDepHourMin() string {
	if m != nil {
		return m.ActualDepHourMin
	}
	return ""
}

func (m *Departure) GetPlannedArrHourMin() string {
	if m != nil {
		return m.PlannedArrHourMin
	}
	return ""
}

func (m *Departure) GetActualArrHourMin() string {
	if m != nil {
		return m.ActualArrHourMin
	}
	return ""
}

func (m *Departure) GetTrainNumber() string {
	if m != nil {
		return m.TrainNumber
	}
	return ""
}

func (m *Departure) GetVia() string {
	if m != nil {
		return m.Via
	}
	return ""
}

func (m *Departure) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Departure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ScheduleRequest struct {
	Carrier     string `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrainNumber string `protobuf:"bytes,2,opt,name=train_number,json=trainNumber,proto3" json:"train_number,omitempty"`
	// If not given, will return latest schedule.
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleRequest) Reset()         { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()    {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{3}
}

func (m *ScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleRequest.Unmarshal(m, b)
}
func (m *ScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleRequest.Merge(m, src)
}
func (m *ScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleRequest.Size(m)
}
func (m *ScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleRequest proto.InternalMessageInfo

func (m *ScheduleRequest) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *ScheduleRequest) GetTrainNumber() string {
	if m != nil {
		return m.TrainNumber
	}
	return ""
}

func (m *ScheduleRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type ScheduleResponse struct {
	TrainNumber          string      `protobuf:"bytes,1,opt,name=train_number,json=trainNumber,proto3" json:"train_number,omitempty"`
	CarrierCode          string      `protobuf:"bytes,2,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	CarrierName          string      `protobuf:"bytes,3,opt,name=carrier_name,json=carrierName,proto3" json:"carrier_name,omitempty"`
	ScheduleItems        []*Schedule `protobuf:"bytes,4,rep,name=schedule_items,json=scheduleItems,proto3" json:"schedule_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ScheduleResponse) Reset()         { *m = ScheduleResponse{} }
func (m *ScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*ScheduleResponse) ProtoMessage()    {}
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{4}
}

func (m *ScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleResponse.Unmarshal(m, b)
}
func (m *ScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleResponse.Marshal(b, m, deterministic)
}
func (m *ScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleResponse.Merge(m, src)
}
func (m *ScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_ScheduleResponse.Size(m)
}
func (m *ScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleResponse proto.InternalMessageInfo

func (m *ScheduleResponse) GetTrainNumber() string {
	if m != nil {
		return m.TrainNumber
	}
	return ""
}

func (m *ScheduleResponse) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *ScheduleResponse) GetCarrierName() string {
	if m != nil {
		return m.CarrierName
	}
	return ""
}

func (m *ScheduleResponse) GetScheduleItems() []*Schedule {
	if m != nil {
		return m.ScheduleItems
	}
	return nil
}

type Schedule struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlannedArrHourMin    string   `protobuf:"bytes,2,opt,name=planned_arr_hour_min,json=plannedArrHourMin,proto3" json:"planned_arr_hour_min,omitempty"`
	PlannedDepHourMin    string   `protobuf:"bytes,3,opt,name=planned_dep_hour_min,json=plannedDepHourMin,proto3" json:"planned_dep_hour_min,omitempty"`
	ActualArrHourMin     string   `protobuf:"bytes,4,opt,name=actual_arr_hour_min,json=actualArrHourMin,proto3" json:"actual_arr_hour_min,omitempty"`
	ActualDepHourMin     string   `protobuf:"bytes,5,opt,name=actual_dep_hour_min,json=actualDepHourMin,proto3" json:"actual_dep_hour_min,omitempty"`
	StationName          string   `protobuf:"bytes,8,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	StationCode          string   `protobuf:"bytes,9,opt,name=station_code,json=stationCode,proto3" json:"station_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_82bd2cd882a959c5, []int{5}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Schedule) GetPlannedArrHourMin() string {
	if m != nil {
		return m.PlannedArrHourMin
	}
	return ""
}

func (m *Schedule) GetPlannedDepHourMin() string {
	if m != nil {
		return m.PlannedDepHourMin
	}
	return ""
}

func (m *Schedule) GetActualArrHourMin() string {
	if m != nil {
		return m.ActualArrHourMin
	}
	return ""
}

func (m *Schedule) GetActualDepHourMin() string {
	if m != nil {
		return m.ActualDepHourMin
	}
	return ""
}

func (m *Schedule) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *Schedule) GetStationCode() string {
	if m != nil {
		return m.StationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*DepartureBoardRequest)(nil), "g2rail.DepartureBoardRequest")
	proto.RegisterType((*DepartureBoardResponse)(nil), "g2rail.DepartureBoardResponse")
	proto.RegisterType((*Departure)(nil), "g2rail.Departure")
	proto.RegisterType((*ScheduleRequest)(nil), "g2rail.ScheduleRequest")
	proto.RegisterType((*ScheduleResponse)(nil), "g2rail.ScheduleResponse")
	proto.RegisterType((*Schedule)(nil), "g2rail.Schedule")
}

func init() { proto.RegisterFile("lib/proto/TrainSchedules.proto", fileDescriptor_82bd2cd882a959c5) }

var fileDescriptor_82bd2cd882a959c5 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0x6e, 0x6d, 0x6f, 0xbb, 0xb6, 0xf3, 0xf8, 0xb0, 0x26, 0x31, 0xad, 0x91, 0x90,
	0xc6, 0x03, 0xad, 0x28, 0x0f, 0x48, 0x48, 0x3c, 0xac, 0x4c, 0x02, 0x84, 0x18, 0x53, 0xe1, 0x89,
	0x97, 0xc8, 0x6d, 0xbc, 0xce, 0x52, 0x12, 0x07, 0xdb, 0xe1, 0xf7, 0xf0, 0x8c, 0x78, 0xe4, 0xd7,
	0xf0, 0x6b, 0x50, 0x5c, 0x27, 0xb3, 0x13, 0x45, 0xbc, 0xc5, 0xf7, 0x1c, 0x9f, 0x7b, 0xe3, 0x7b,
	0x74, 0xe0, 0x2c, 0x66, 0x9b, 0x45, 0x26, 0xb8, 0xe2, 0x8b, 0xaf, 0x82, 0xb0, 0xf4, 0xcb, 0xf6,
	0x8e, 0x46, 0x79, 0x4c, 0xe5, 0x5c, 0x17, 0xd1, 0xe1, 0x6e, 0x29, 0x08, 0x8b, 0x83, 0xd7, 0xf0,
	0xf0, 0x8a, 0x66, 0x44, 0xa8, 0x5c, 0xd0, 0x15, 0x27, 0x22, 0x5a, 0xd3, 0xef, 0x39, 0x95, 0x0a,
	0xcd, 0x60, 0x24, 0x15, 0x51, 0x8c, 0xa7, 0xe1, 0x96, 0x47, 0x14, 0x7b, 0xe7, 0xde, 0xc5, 0x60,
	0x3d, 0x34, 0xb5, 0xb7, 0x3c, 0xa2, 0xc1, 0x47, 0x78, 0x54, 0xbf, 0x2b, 0x33, 0x9e, 0x4a, 0x8a,
	0x5e, 0x00, 0x44, 0x25, 0x22, 0xb1, 0x77, 0xee, 0x5f, 0x0c, 0x97, 0xc7, 0xf3, 0x7d, 0xcb, 0x79,
	0x75, 0x67, 0x6d, 0x91, 0x82, 0xbf, 0x3e, 0x0c, 0x2a, 0x04, 0x3d, 0x85, 0x71, 0x85, 0xd9, 0xfd,
	0x8f, 0xaa, 0x6a, 0x31, 0x81, 0x4b, 0x4b, 0x49, 0x42, 0x71, 0xa7, 0x46, 0xbb, 0x26, 0x09, 0x45,
	0xcf, 0x60, 0x1a, 0x51, 0xa9, 0x58, 0x6a, 0xfd, 0x8f, 0xaf, 0x89, 0x13, 0xab, 0xae, 0x15, 0x6b,
	0x54, 0xad, 0xd9, 0x6d, 0x50, 0xb5, 0xea, 0x02, 0x1e, 0x64, 0x31, 0x49, 0x53, 0x1a, 0x85, 0x11,
	0xcd, 0xc2, 0x3b, 0x9e, 0x8b, 0x30, 0x61, 0x29, 0x3e, 0xd0, 0xf4, 0x63, 0x83, 0x5d, 0xd1, 0xec,
	0x3d, 0xcf, 0xc5, 0x27, 0x96, 0xa2, 0xe7, 0x70, 0x42, 0xb6, 0x2a, 0x27, 0xb1, 0xcb, 0x3f, 0xd4,
	0xfc, 0xe9, 0x1e, 0xb2, 0xe8, 0x96, 0x3e, 0x11, 0xe2, 0x9e, 0xdf, 0x73, 0xf4, 0x2f, 0x85, 0x68,
	0xea, 0x3b, 0xfc, 0xbe, 0xad, 0x6f, 0xd1, 0x67, 0x30, 0x52, 0x85, 0x35, 0xc2, 0x34, 0x4f, 0x36,
	0x54, 0xe0, 0xc1, 0x7e, 0xc3, 0xba, 0x76, 0xad, 0x4b, 0x68, 0x0a, 0xfe, 0x0f, 0x46, 0x30, 0x68,
	0xa4, 0xf8, 0x44, 0xa7, 0xd0, 0xcf, 0x62, 0xa2, 0x6e, 0xb9, 0x48, 0xf0, 0x50, 0x97, 0xab, 0x33,
	0xc2, 0xd0, 0x4b, 0xa8, 0x94, 0x64, 0x47, 0xf1, 0x48, 0x43, 0xe5, 0x31, 0xd8, 0xc0, 0xa4, 0x34,
	0x60, 0xe9, 0x2f, 0x0c, 0xbd, 0x2d, 0x11, 0x82, 0x51, 0x61, 0x56, 0x5b, 0x1e, 0x1b, 0x73, 0x75,
	0x9a, 0x73, 0x21, 0xe8, 0x46, 0x44, 0x95, 0x4b, 0xd4, 0xdf, 0xc1, 0x1f, 0x0f, 0xa6, 0xf7, 0x4d,
	0x8c, 0x11, 0xeb, 0x5a, 0x5e, 0x53, 0x6b, 0x06, 0x23, 0xd3, 0x79, 0x6f, 0x0c, 0xd3, 0xce, 0xd4,
	0xb4, 0x29, 0x2c, 0x8a, 0x36, 0x84, 0xef, 0x50, 0xb4, 0x19, 0x5e, 0xc1, 0x58, 0x9a, 0xe6, 0x21,
	0x53, 0x34, 0x91, 0xb8, 0xab, 0x5d, 0x3f, 0x2d, 0x5d, 0x5f, 0x8d, 0x76, 0x54, 0xf2, 0x3e, 0x14,
	0xb4, 0xe0, 0x77, 0x07, 0xfa, 0x25, 0xe6, 0xbc, 0xae, 0x57, 0x7b, 0xdd, 0x36, 0x3b, 0x74, 0xda,
	0xec, 0xd0, 0xe6, 0x4f, 0xff, 0xff, 0xfe, 0x74, 0x1a, 0x74, 0x5b, 0xfc, 0xd3, 0x62, 0xe7, 0x83,
	0x16, 0x3b, 0x5b, 0x81, 0xa2, 0x1f, 0xb1, 0xef, 0x04, 0x8a, 0x7e, 0xc4, 0x7a, 0xe6, 0x0c, 0x1a,
	0x99, 0xb3, 0xfc, 0xe9, 0xc1, 0xd8, 0x0d, 0x34, 0xf4, 0x19, 0xc6, 0x6e, 0x0c, 0xa1, 0x27, 0x8d,
	0xa8, 0xb1, 0xa3, 0xed, 0xf4, 0xac, 0x0d, 0x36, 0xa6, 0x79, 0x63, 0x6d, 0xe4, 0x71, 0x63, 0x7f,
	0x46, 0x04, 0x37, 0x81, 0xfd, 0xf5, 0xd5, 0x25, 0x8c, 0x19, 0x9f, 0xef, 0x44, 0xb6, 0x35, 0x94,
	0xd5, 0x89, 0x3b, 0xf1, 0x4d, 0x91, 0xc0, 0x37, 0xde, 0x37, 0x93, 0xc1, 0xbf, 0x3a, 0x93, 0x77,
	0xcb, 0x75, 0x21, 0xa5, 0x81, 0x4d, 0x7e, 0xbb, 0x39, 0xd4, 0x21, 0xfd, 0xf2, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x53, 0xa4, 0xfc, 0x83, 0xc6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrainSchedulesClient is the client API for TrainSchedules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainSchedulesClient interface {
	// Retrieve real time departure information of a given station
	DepartureBoard(ctx context.Context, in *DepartureBoardRequest, opts ...grpc.CallOption) (*DepartureBoardResponse, error)
	// Retrieve a train schedule information of a given station
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
}

type trainSchedulesClient struct {
	cc *grpc.ClientConn
}

func NewTrainSchedulesClient(cc *grpc.ClientConn) TrainSchedulesClient {
	return &trainSchedulesClient{cc}
}

func (c *trainSchedulesClient) DepartureBoard(ctx context.Context, in *DepartureBoardRequest, opts ...grpc.CallOption) (*DepartureBoardResponse, error) {
	out := new(DepartureBoardResponse)
	err := c.cc.Invoke(ctx, "/g2rail.TrainSchedules/DepartureBoard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainSchedulesClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, "/g2rail.TrainSchedules/Schedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainSchedulesServer is the server API for TrainSchedules service.
type TrainSchedulesServer interface {
	// Retrieve real time departure information of a given station
	DepartureBoard(context.Context, *DepartureBoardRequest) (*DepartureBoardResponse, error)
	// Retrieve a train schedule information of a given station
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
}

func RegisterTrainSchedulesServer(s *grpc.Server, srv TrainSchedulesServer) {
	s.RegisterService(&_TrainSchedules_serviceDesc, srv)
}

func _TrainSchedules_DepartureBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartureBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainSchedulesServer).DepartureBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.TrainSchedules/DepartureBoard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainSchedulesServer).DepartureBoard(ctx, req.(*DepartureBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainSchedules_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainSchedulesServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/g2rail.TrainSchedules/Schedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainSchedulesServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrainSchedules_serviceDesc = grpc.ServiceDesc{
	ServiceName: "g2rail.TrainSchedules",
	HandlerType: (*TrainSchedulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepartureBoard",
			Handler:    _TrainSchedules_DepartureBoard_Handler,
		},
		{
			MethodName: "Schedule",
			Handler:    _TrainSchedules_Schedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/proto/TrainSchedules.proto",
}
